/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/hashes.o /home/chronize/Documents/projects/nimkernel/nimcache/hashes.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX21HEX26_128019)(NI h, NI val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, HEX21HEX24_128048)(NI h);
N_NIMCALL(NI, hashdata_128076)(void* data, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, hash_128401)(void* x);
static N_INLINE(NI, hash_128804)(NI x);
static N_INLINE(NI, hash_128814)(NI64 x);
static N_INLINE(NI, hash_128824)(NIM_CHAR x);
N_NIMCALL(NI, hash_128842)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, hashignorestyle_128888)(NimStringDesc* x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, hashignorecase_128980)(NimStringDesc* x);
static N_INLINE(NI, hash_129082)(NF x);
extern TFrame* frameptr_16242;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NI, HEX21HEX26_128019)(NI h, NI val) {
	NI result;
	nimfr("!&", "hashes.nim")
	result = 0;
	nimln(51, "hashes.nim");
	nimln(51, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)(val));
	nimln(52, "hashes.nim");
	nimln(52, "hashes.nim");
	nimln(52, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(10))));
	nimln(53, "hashes.nim");
	nimln(53, "hashes.nim");
	nimln(53, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(6)));
	popFrame();
	return result;
}

static N_INLINE(NI, HEX21HEX24_128048)(NI h) {
	NI result;
	nimfr("!$", "hashes.nim")
	result = 0;
	nimln(58, "hashes.nim");
	nimln(58, "hashes.nim");
	nimln(58, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(3))));
	nimln(59, "hashes.nim");
	nimln(59, "hashes.nim");
	nimln(59, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(11)));
	nimln(60, "hashes.nim");
	nimln(60, "hashes.nim");
	nimln(60, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(15))));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashdata_128076)(void* data, NI size) {
	NI result;
	NI h;
	NCSTRING p;
	NI i;
	NI s;
	nimfr("hashData", "hashes.nim")
	result = 0;
	nimln(64, "hashes.nim");
	h = 0;
	nimln(69, "hashes.nim");
	p = ((NCSTRING) (data));
	nimln(70, "hashes.nim");
	i = 0;
	nimln(71, "hashes.nim");
	s = size;
	{
		nimln(72, "hashes.nim");
		while (1) {
			nimln(72, "hashes.nim");
			if (!(0 < s)) goto LA2;
			nimln(73, "hashes.nim");
			nimln(73, "hashes.nim");
			h = HEX21HEX26_128019(h, ((NI) (((NU8)(p[i])))));
			nimln(74, "hashes.nim");
			i = addInt(i, 1);
			nimln(75, "hashes.nim");
			s = subInt(s, 1);
		} LA2: ;
	}
	nimln(76, "hashes.nim");
	result = HEX21HEX24_128048(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_128401)(void* x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(95, "hashes.nim");
	nimln(95, "hashes.nim");
	result = (NI)((NU64)(((NI) (x))) >> (NU64)(3));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_128804)(NI x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(107, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, hash_128814)(NI64 x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(111, "hashes.nim");
	nimln(111, "hashes.nim");
	result = ((NI) (((NI32)(NU32)(NU64)(x))));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_128824)(NIM_CHAR x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(115, "hashes.nim");
	nimln(115, "hashes.nim");
	result = ((NI) (((NU8)(x))));
	popFrame();
	return result;
}

N_NIMCALL(NI, hash_128842)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(119, "hashes.nim");
	h = 0;
	{
		NI i_128857;
		NI HEX3Atmp_128868;
		NI TMP275;
		NI res_128871;
		i_128857 = 0;
		HEX3Atmp_128868 = 0;
		nimln(120, "hashes.nim");
		nimln(120, "hashes.nim");
		nimln(120, "hashes.nim");
		TMP275 = subInt(x->Sup.len, 1);
		HEX3Atmp_128868 = (NI64)(TMP275);
		nimln(1576, "system.nim");
		res_128871 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				nimln(1577, "system.nim");
				if (!(res_128871 <= HEX3Atmp_128868)) goto LA3;
				nimln(1576, "system.nim");
				i_128857 = res_128871;
				nimln(121, "hashes.nim");
				nimln(121, "hashes.nim");
				if ((NU)(i_128857) > (NU)(x->Sup.len)) raiseIndexError();
				h = HEX21HEX26_128019(h, ((NI) (((NU8)(x->data[i_128857])))));
				nimln(1579, "system.nim");
				res_128871 = addInt(res_128871, 1);
			} LA3: ;
		}
	}
	nimln(122, "hashes.nim");
	result = HEX21HEX24_128048(h);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashignorestyle_128888)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result = 0;
	nimln(126, "hashes.nim");
	h = 0;
	{
		NI i_128903;
		NI HEX3Atmp_128957;
		NI TMP276;
		NI res_128960;
		i_128903 = 0;
		HEX3Atmp_128957 = 0;
		nimln(127, "hashes.nim");
		nimln(127, "hashes.nim");
		nimln(127, "hashes.nim");
		TMP276 = subInt(x->Sup.len, 1);
		HEX3Atmp_128957 = (NI64)(TMP276);
		nimln(1576, "system.nim");
		res_128960 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				nimln(1577, "system.nim");
				if (!(res_128960 <= HEX3Atmp_128957)) goto LA3;
				nimln(1576, "system.nim");
				i_128903 = res_128960;
				{
					NIM_CHAR c;
					nimln(128, "hashes.nim");
					if ((NU)(i_128903) > (NU)(x->Sup.len)) raiseIndexError();
					c = x->data[i_128903];
					nimln(129, "hashes.nim");
					{
						nimln(129, "hashes.nim");
						if (!((NU8)(c) == (NU8)(95))) goto LA7;
						nimln(130, "hashes.nim");
						goto LA4;
					}
					LA7: ;
					nimln(131, "hashes.nim");
					{
						NI TMP277;
						nimln(131, "hashes.nim");
						if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA11;
						nimln(132, "hashes.nim");
						nimln(132, "hashes.nim");
						nimln(132, "hashes.nim");
						nimln(132, "hashes.nim");
						TMP277 = addInt(((NI) (((NU8)(c)))), 32);
						c = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP277), 0, 255))));
					}
					LA11: ;
					nimln(133, "hashes.nim");
					nimln(133, "hashes.nim");
					h = HEX21HEX26_128019(h, ((NI) (((NU8)(c)))));
				} LA4: ;
				nimln(1579, "system.nim");
				res_128960 = addInt(res_128960, 1);
			} LA3: ;
		}
	}
	nimln(134, "hashes.nim");
	result = HEX21HEX24_128048(h);
	popFrame();
	return result;
}

N_NIMCALL(NI, hashignorecase_128980)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hashIgnoreCase", "hashes.nim")
	result = 0;
	nimln(138, "hashes.nim");
	h = 0;
	{
		NI i_128995;
		NI HEX3Atmp_129048;
		NI TMP278;
		NI res_129051;
		i_128995 = 0;
		HEX3Atmp_129048 = 0;
		nimln(139, "hashes.nim");
		nimln(139, "hashes.nim");
		nimln(139, "hashes.nim");
		TMP278 = subInt(x->Sup.len, 1);
		HEX3Atmp_129048 = (NI64)(TMP278);
		nimln(1576, "system.nim");
		res_129051 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				NIM_CHAR c;
				nimln(1577, "system.nim");
				if (!(res_129051 <= HEX3Atmp_129048)) goto LA3;
				nimln(1576, "system.nim");
				i_128995 = res_129051;
				nimln(140, "hashes.nim");
				if ((NU)(i_128995) > (NU)(x->Sup.len)) raiseIndexError();
				c = x->data[i_128995];
				nimln(141, "hashes.nim");
				{
					NI TMP279;
					nimln(141, "hashes.nim");
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6;
					nimln(142, "hashes.nim");
					nimln(142, "hashes.nim");
					nimln(142, "hashes.nim");
					nimln(142, "hashes.nim");
					TMP279 = addInt(((NI) (((NU8)(c)))), 32);
					c = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP279), 0, 255))));
				}
				LA6: ;
				nimln(143, "hashes.nim");
				nimln(143, "hashes.nim");
				h = HEX21HEX26_128019(h, ((NI) (((NU8)(c)))));
				nimln(1579, "system.nim");
				res_129051 = addInt(res_129051, 1);
			} LA3: ;
		}
	}
	nimln(144, "hashes.nim");
	result = HEX21HEX24_128048(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_129082)(NF x) {
	NI result;
	NF y;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(153, "hashes.nim");
	nimln(153, "hashes.nim");
	y = ((NF)(x) + (NF)(1.0000000000000000e+00));
	nimln(154, "hashes.nim");
	result = (*((NI*) ((&y))));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesInit)(void) {
	nimfr("hashes", "hashes.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_hashesDatInit)(void) {
}

