/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/history.o /home/chronize/Documents/projects/nimkernel/nimcache/history.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void, TY141071) (NCSTRING a2);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP301, "libreadline.so.6", 16);
STRING_LITERAL(TMP302, "libreadline.so.6.0", 18);
STRING_LITERAL(TMP303, "libreadline.so.6(|.0)", 21);
static void* TMP300;
TY141071 Dl_141070;
extern TFrame* frameptr_16242;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_historyInit)(void) {
	nimfr("history", "history.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_historyDatInit)(void) {
if (!((TMP300 = nimLoadLibrary((NimStringDesc*) &TMP301))
||(TMP300 = nimLoadLibrary((NimStringDesc*) &TMP302))
)) nimLoadLibraryError((NimStringDesc*) &TMP303);
	Dl_141070 = (TY141071) nimGetProcAddr(TMP300, "add_history");
}

