/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc -c  -w -I$lib -ffreestanding -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/ioutils.o /home/chronize/Documents/projects/nimkernel/nimcache/ioutils.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tpos9009 tpos9009;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tpos9009 {
NI Field0;
NI Field1;
};
N_NIMCALL(NU8, makecolor_9057)(NU8 bg, NU8 fg);
N_NIMCALL(NU16, makeentry_9107)(NIM_CHAR c, NU8 color);
N_NIMCALL(void, writechar_9150)(NU16* vram, NU16 entry, tpos9009 pos);
N_NIMCALL(NU8, nextcolor_9170)(NU8 color, NU16 skip);

N_NIMCALL(NU8, makecolor_9057)(NU8 bg, NU8 fg) {
	NU8 result;
	result = 0;
	result = (NU8)(((NU8) (fg)) | (NU8)((NU8)(((NU8) (bg))) << (NU8)(((NU8) 4))));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NU16, makeentry_9107)(NIM_CHAR c, NU8 color) {
	NU16 result;
	NU16 c16;
	NU16 color16;
	result = 0;
	c16 = ((NU16) (((NU8)(c))));
	color16 = ((NU16) (color));
	result = (NU16)(c16 | (NU16)((NU16)(color16) << (NU16)(((NU16) 8))));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, screenclear_9310)(NU16* videomem, NU8 color) {
	NU8 attr;
	NU16 space;
	NI i;
	attr = makecolor_9057(color, color);
	space = makeentry_9107(32, attr);
	i = 0;
	{
		while (1) {
			if (!((NU32)(i) <= (NU32)(2000))) goto LA2;
			videomem[(i)- 0] = space;
			i += 1;
		} LA2: ;
	}
}

N_NIMCALL(void, writechar_9150)(NU16* vram, NU16 entry, tpos9009 pos) {
	NI index;
	index = (NI32)((NI32)(80 * pos.Field1) + pos.Field0);
	vram[(index)- 0] = entry;
}

N_NIMCALL(void, writestring_9271)(NU16* vram, NimStringDesc* text, NU8 color, tpos9009 pos) {
	{
		NI i_9287;
		NI HEX3Atmp_9290;
		NI res_9293;
		i_9287 = 0;
		HEX3Atmp_9290 = 0;
		HEX3Atmp_9290 = (NI32)(text->Sup.len - 1);
		res_9293 = 0;
		{
			while (1) {
				NU16 LOC4;
				tpos9009 LOC5;
				if (!(res_9293 <= HEX3Atmp_9290)) goto LA3;
				i_9287 = res_9293;
				LOC4 = 0;
				LOC4 = makeentry_9107(text->data[i_9287], color);
				LOC5.Field0 = (NI32)(pos.Field0 + i_9287);
				LOC5.Field1 = pos.Field1;
				writechar_9150(vram, LOC4, LOC5);
				res_9293 += 1;
			} LA3: ;
		}
	}
}

N_NIMCALL(NU8, nextcolor_9170)(NU8 color, NU16 skip) {
	NU8 result;
	result = 0;
	{
		if (!(color == ((NU8) 15))) goto LA3;
		result = ((NU8) 0);
	}
	goto LA1;
	LA3: ;
	{
		result = ((NU8) ((NI32)(((NI) (color)) + 1)));
	}
	LA1: ;
	{
		if (!((skip &(1<<((result)&15)))!=0)) goto LA8;
		result = nextcolor_9170(result, skip);
	}
	LA8: ;
	return result;
}

N_NIMCALL(void, rainbow_9163)(NU16* vram, NimStringDesc* text, tpos9009 pos) {
	NU8 colorbg;
	NU8 colorfg;
	colorbg = ((NU8) 8);
	colorfg = ((NU8) 1);
	{
		NI i_9243;
		NI HEX3Atmp_9248;
		NI res_9251;
		i_9243 = 0;
		HEX3Atmp_9248 = 0;
		HEX3Atmp_9248 = (NI32)(text->Sup.len - 1);
		res_9251 = 0;
		{
			while (1) {
				NU8 attr;
				NU16 LOC4;
				tpos9009 LOC5;
				if (!(res_9251 <= HEX3Atmp_9248)) goto LA3;
				i_9243 = res_9251;
				colorfg = nextcolor_9170(colorfg, 9019);
				attr = makecolor_9057(colorbg, colorfg);
				LOC4 = 0;
				LOC4 = makeentry_9107(text->data[i_9243], attr);
				LOC5.Field0 = (NI32)(pos.Field0 + i_9243);
				LOC5.Field1 = pos.Field1;
				writechar_9150(vram, LOC4, LOC5);
				res_9251 += 1;
			} LA3: ;
		}
	}
}
NIM_EXTERNC N_NOINLINE(void, HEX00_ioutilsInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_ioutilsDatInit)(void) {
}

