/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc -c  -w -I$lib -ffreestanding -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/main.o /home/chronize/Documents/projects/nimkernel/nimcache/main.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct tmultibootheader26007 tmultibootheader26007;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tpos9009 tpos9009;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tpos9009 {
NI Field0;
NI Field1;
};
struct  tmultibootheader26007  {
char dummy;
};
N_NIMCALL(void, kmain)(tmultibootheader26007* mbheader, NI magic);
N_NIMCALL(void, screenclear_9310)(NU16* videomem, NU8 color);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NU8, makecolor_9057)(NU8 bg, NU8 fg);
N_NIMCALL(void, writestring_9271)(NU16* vram, NimStringDesc* text, NU8 color, tpos9009 pos);
N_NIMCALL(void, rainbow_9163)(NU16* vram, NimStringDesc* text, tpos9009 pos);
NIM_EXTERNC N_NOINLINE(void, HEX00_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_ioutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_ioutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, mainInit)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit)(void);
STRING_LITERAL(TMP12, "Nim", 3);
NIM_CONST tpos9009 TMP13 = {25,
9}
;
STRING_LITERAL(TMP14, "Expressive. Efficient. Elegant.", 31);
NIM_CONST tpos9009 TMP15 = {25,
10}
;
STRING_LITERAL(TMP16, "It\'s pure pleasure.", 19);
NIM_CONST tpos9009 TMP17 = {25,
11}
;

N_NIMCALL(void, kmain)(tmultibootheader26007* mbheader, NI magic) {
	NU16* vram;
	NI x;
	NU16 outofbounds;
	NU8 attr;
	{
		if (!!((magic == 732803074))) goto LA3;
	}
	LA3: ;
	vram = ((NU16*) 753664);
	screenclear_9310(vram, ((NU8) 14));
	x = 65001;
	if ((NU)(x) > (NU)(65000)) raiseIndexError();
	outofbounds = vram[(x)- 0];
	attr = makecolor_9057(((NU8) 14), ((NU8) 8));
	writestring_9271(vram, ((NimStringDesc*) &TMP12), attr, TMP13);
	writestring_9271(vram, ((NimStringDesc*) &TMP14), attr, TMP15);
	rainbow_9163(vram, ((NimStringDesc*) &TMP16), TMP17);
}
void PreMainInner() {
	systemInit();
	HEX00_unsignedDatInit();
	HEX00_ioutilsDatInit();
	mainDatInit();
	HEX00_unsignedInit();
	HEX00_ioutilsInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	mainInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

NIM_EXTERNC N_NOINLINE(void, mainInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit)(void) {
}

