/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/math.o /home/chronize/Documents/projects/nimkernel/nimcache/math.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <math.h>

#include <stdlib.h>
typedef struct runningstat133044 runningstat133044;
struct  runningstat133044  {
NI N;
NF Sum;
NF Min;
NF Max;
NF Mean;
NF Oldm;
NF Olds;
NF News;
};
N_NIMCALL(NU8, classify_131426)(NF x);
N_NIMCALL(NI, binom_131442)(NI n, NI k);
N_NIMCALL(NI, fac_131481)(NI n);
N_NIMCALL(NIM_BOOL, ispoweroftwo_131518)(NI x);
N_NIMCALL(NI, nextpoweroftwo_131528)(NI x);
N_NIMCALL(NI, countbits32_132028)(NI32 n);
N_NIMCALL(NF, sum_132095)(NF* x_132101, NI x_132101Len0);
N_NIMCALL(NF, mean_132088)(NF* x, NI xLen0);
N_NIMCALL(NF, variance_132176)(NF* x, NI xLen0);
N_NIMCALL(NF, log2_132255)(NF x);
N_NIMCALL(NF, random_132229)(NF max);
N_NIMCALL(void, randomize_132235)(void);
N_NIMCALL(void, randomize_132240)(NI seed);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI, random_132223)(NI max);
N_NIMCALL(NF, mod_133004)(NF x, NF y);
N_NIMCALL(void, push_133061)(runningstat133044* s, NF x);
N_NIMCALL(void, push_133085)(runningstat133044* s, NI x);
N_NIMCALL(NF, variance_133096)(runningstat133044* s);
N_NIMCALL(NF, standarddeviation_133107)(runningstat133044* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_16242;

N_NIMCALL(NU8, classify_131426)(NF x) {
	NU8 result;
	result = 0;
	{
		if (!(x == 0.0)) goto LA3;
		{
			if (!(((NF)(1.0000000000000000e+00) / (NF)(x)) == INF)) goto LA7;
			result = ((NU8) 2);
			goto BeforeRet;
		}
		goto LA5;
		LA7: ;
		{
			result = ((NU8) 3);
			goto BeforeRet;
		}
		LA5: ;
	}
	LA3: ;
	{
		if (!(((NF)(x) * (NF)(5.0000000000000000e-01)) == x)) goto LA12;
		{
			if (!(0.0 < x)) goto LA16;
			result = ((NU8) 5);
			goto BeforeRet;
		}
		goto LA14;
		LA16: ;
		{
			result = ((NU8) 6);
			goto BeforeRet;
		}
		LA14: ;
	}
	LA12: ;
	{
		if (!!((x == x))) goto LA21;
		result = ((NU8) 4);
		goto BeforeRet;
	}
	LA21: ;
	result = ((NU8) 0);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, binom_131442)(NI n, NI k) {
	NI result;
	result = 0;
	{
		if (!(k <= 0)) goto LA3;
		result = 1;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!(n < (NI64)(2 * k))) goto LA7;
		result = binom_131442(n, (NI64)(n - k));
		goto BeforeRet;
	}
	LA7: ;
	result = n;
	{
		NI i_131460;
		NI res_131464;
		i_131460 = 0;
		res_131464 = 2;
		{
			while (1) {
				if (!(res_131464 <= k)) goto LA11;
				i_131460 = res_131464;
				result = (NI64)((NI64)(result * (NI64)((NI64)(n + 1) - i_131460)) / i_131460);
				res_131464 += 1;
			} LA11: ;
		}
	}
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, fac_131481)(NI n) {
	NI result;
	result = 0;
	result = 1;
	{
		NI i_131497;
		NI res_131501;
		i_131497 = 0;
		res_131501 = 2;
		{
			while (1) {
				if (!(res_131501 <= n)) goto LA3;
				i_131497 = res_131501;
				result = (NI64)(result * i_131497);
				res_131501 += 1;
			} LA3: ;
		}
	}
	return result;
}

N_NIMCALL(NIM_BOOL, ispoweroftwo_131518)(NI x) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = !((x == 0));
	if (!(LOC1)) goto LA2;
	LOC1 = ((NI)(x & (NI64)(x - 1)) == 0);
	LA2: ;
	result = LOC1;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, nextpoweroftwo_131528)(NI x) {
	NI result;
	result = 0;
	result = (NI64)(x - 1);
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(32)));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(4)));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(2)));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(1)));
	result += ((NI) ((NI64)(1 + ((NI) ((x <= 0))))));
	return result;
}

N_NIMCALL(NI, countbits32_132028)(NI32 n) {
	NI result;
	NI32 v;
	result = 0;
	v = n;
	v = (NI32)((NU32)(v) - (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 1))) & ((NI32) 1431655765))));
	v = (NI32)((NU32)((NI32)(v & ((NI32) 858993459))) + (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 2))) & ((NI32) 858993459))));
	result = ((NI) ((NI32)((NU32)((NI32)((NU32)((NI32)((NI32)((NU32)(v) + (NU32)((NI32)((NU32)(v) >> (NU32)(((NI32) 4))))) & ((NI32) 252645135))) * (NU32)(((NI32) 16843009)))) >> (NU32)(((NI32) 24)))));
	return result;
}

N_NIMCALL(NF, sum_132095)(NF* x_132101, NI x_132101Len0) {
	NF result;
	result = 0;
	{
		NF i_132146;
		NI i_132150;
		i_132146 = 0;
		i_132150 = 0;
		{
			while (1) {
				if (!(i_132150 < x_132101Len0)) goto LA3;
				i_132146 = x_132101[i_132150];
				result = ((NF)(result) + (NF)(i_132146));
				i_132150 += 1;
			} LA3: ;
		}
	}
	return result;
}

N_NIMCALL(NF, mean_132088)(NF* x, NI xLen0) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = sum_132095(x, xLen0);
	result = ((NF)(LOC1) / (NF)(((double) (xLen0))));
	return result;
}

N_NIMCALL(NF, variance_132176)(NF* x, NI xLen0) {
	NF result;
	NF m;
	result = 0;
	result = 0.0;
	m = mean_132088(x, xLen0);
	{
		NI i_132193;
		NI HEX3Atmp_132203;
		NI res_132206;
		i_132193 = 0;
		HEX3Atmp_132203 = 0;
		HEX3Atmp_132203 = (xLen0-1);
		res_132206 = 0;
		{
			while (1) {
				NF diff;
				if (!(res_132206 <= HEX3Atmp_132203)) goto LA3;
				i_132193 = res_132206;
				diff = ((NF)(x[i_132193]) - (NF)(m));
				result = ((NF)(result) + (NF)(((NF)(diff) * (NF)(diff))));
				res_132206 += 1;
			} LA3: ;
		}
	}
	result = ((NF)(result) / (NF)(((double) (xLen0))));
	return result;
}

N_NIMCALL(NF, log2_132255)(NF x) {
	NF result;
	NF LOC1;
	NF LOC2;
	result = 0;
	LOC1 = 0;
	LOC1 = log(x);
	LOC2 = 0;
	LOC2 = log(2.0000000000000000e+00);
	result = ((NF)(LOC1) / (NF)(LOC2));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NF, random_132229)(NF max) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = drand48();
	result = ((NF)(LOC1) * (NF)(max));
	return result;
}

N_NIMCALL(void, randomize_132240)(NI seed) {
	srand(((int) (seed)));
	srand48(seed);
}

N_NIMCALL(void, randomize_132235)(void) {
	union { NF source; NI dest; } LOC1;
	LOC1.source = ntepochTime();
	randomize_132240(LOC1.dest);
}

N_NIMCALL(NI, random_132223)(NI max) {
	NI result;
	int LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = rand();
	result = (NI64)(((NI) (LOC1)) % max);
	return result;
}

N_NIMCALL(NF, mod_133004)(NF x, NF y) {
	NF result;
	result = 0;
	{
		if (!(y == 0.0)) goto LA3;
		result = x;
	}
	goto LA1;
	LA3: ;
	{
		NF LOC6;
		LOC6 = 0;
		LOC6 = floor(((NF)(x) / (NF)(y)));
		result = ((NF)(x) - (NF)(((NF)(y) * (NF)(LOC6))));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, push_133061)(runningstat133044* s, NF x) {
	(*s).N += 1;
	{
		if (!((*s).N == 1)) goto LA3;
		(*s).Min = x;
		(*s).Max = x;
		(*s).Oldm = x;
		(*s).Mean = x;
		(*s).Olds = 0.0;
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!(x < (*s).Min)) goto LA8;
			(*s).Min = x;
		}
		LA8: ;
		{
			if (!((*s).Max < x)) goto LA12;
			(*s).Max = x;
		}
		LA12: ;
		(*s).Mean = ((NF)((*s).Oldm) + (NF)(((NF)(((NF)(x) - (NF)((*s).Oldm))) / (NF)(((double) ((*s).N))))));
		(*s).News = ((NF)((*s).Olds) + (NF)(((NF)(((NF)(x) - (NF)((*s).Oldm))) * (NF)(((NF)(x) - (NF)((*s).Mean))))));
		(*s).Oldm = (*s).Mean;
		(*s).Olds = (*s).News;
	}
	LA1: ;
	(*s).Sum = ((NF)((*s).Sum) + (NF)(x));
}

N_NIMCALL(void, push_133085)(runningstat133044* s, NI x) {
	push_133061(s, ((double) (x)));
}

N_NIMCALL(NF, variance_133096)(runningstat133044* s) {
	NF result;
	result = 0;
	{
		if (!(1 < (*s).N)) goto LA3;
		result = ((NF)((*s).News) / (NF)(((double) ((NI64)((*s).N - 1)))));
	}
	LA3: ;
	return result;
}

N_NIMCALL(NF, standarddeviation_133107)(runningstat133044* s) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = variance_133096(s);
	result = sqrt(LOC1);
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_mathInit)(void) {
	nimfr("math", "math.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_mathDatInit)(void) {
}

