/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/nakefile.o /home/chronize/Documents/projects/nimkernel/nimcache/nakefile.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <string.h>
typedef struct TY145248 TY145248;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct orderedtable143031 orderedtable143031;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct ptaskHEX3Aobjecttype143013 ptaskHEX3Aobjecttype143013;
typedef struct orderedkeyvaluepairseq143034 orderedkeyvaluepairseq143034;
typedef struct orderedkeyvaluepair143037 orderedkeyvaluepair143037;
typedef struct TY145307 TY145307;
typedef struct TY145346 TY145346;
struct  TY145248  {
NI HEX3Astate;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct orderedkeyvaluepair143037 {
NU8 Field0;
NI Field1;
NimStringDesc* Field2;
ptaskHEX3Aobjecttype143013* Field3;
};
struct  orderedtable143031  {
orderedkeyvaluepairseq143034* Data;
NI Counter;
NI First;
NI Last;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} ttaskfunction143010;
struct  TY145307  {
NI HEX3Astate;
};
typedef NimStringDesc* TY96973[1];
typedef NimStringDesc* TY143461[2];
struct  TY145346  {
NI HEX3Astate;
};
struct  ptaskHEX3Aobjecttype143013  {
NimStringDesc* Desc;
ttaskfunction143010 Action;
};
typedef N_CLOSURE_PTR(void, TMP403) (void);
struct orderedkeyvaluepairseq143034 {
  TGenericSeq Sup;
  orderedkeyvaluepair143037 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, TMP380)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, HEX5BHEX5DHEX3D_145024)(orderedtable143031* t_145033, NimStringDesc* key_145037, ptaskHEX3Aobjecttype143013* val_145039);
N_NIMCALL(void, enlarge_145069)(orderedtable143031* t_145078);
N_NIMCALL(void, rawinsert_145128)(orderedtable143031* t_145137, orderedkeyvaluepairseq143034** data_145145, NimStringDesc* key_145149, ptaskHEX3Aobjecttype143013* val_145151);
N_NIMCALL(ptaskHEX3Aobjecttype143013*, newtask_143242)(NimStringDesc* desc, ttaskfunction143010 action);
N_CLOSURE(void, HEX3Aanonymous_145014)(void* ClEnv);
N_NIMCALL(void, nosremoveFile)(NimStringDesc* file);
N_NIMCALL(void, nosremoveDir)(NimStringDesc* dir);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, TMP390)(void* p, NI op);
N_CLOSURE(void, HEX3Aanonymous_145260)(void* ClEnv);
N_NIMCALL(NIM_BOOL, direshell_143398)(NimStringDesc** cmd, NI cmdLen0);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, TMP400)(void* p, NI op);
N_CLOSURE(void, HEX3Aanonymous_145319)(void* ClEnv);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
static N_INLINE(void, runtask_143249)(NimStringDesc* name);
N_NIMCALL(ptaskHEX3Aobjecttype143013*, HEX5BHEX5D_143288)(orderedtable143031* t_143295, NimStringDesc* key_143298);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseoptInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseoptDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_rltypedefsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_rltypedefsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_readlineInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_readlineDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_historyInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_historyDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_rdstdinInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_rdstdinDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nake_nakeInit)(void);
NIM_EXTERNC N_NOINLINE(void, nake_nakeDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nakefileInit)(void);
NIM_EXTERNC N_NOINLINE(void, nakefileDatInit)(void);
STRING_LITERAL(TMP382, "clean", 5);
STRING_LITERAL(TMP383, "Removes build files.", 20);
STRING_LITERAL(TMP384, "boot.o", 6);
STRING_LITERAL(TMP385, "main.bin", 8);
STRING_LITERAL(TMP388, "nimcache", 8);
STRING_LITERAL(TMP389, "Done.", 5);
STRING_LITERAL(TMP391, "build", 5);
STRING_LITERAL(TMP392, "Builds the operating system.", 28);
STRING_LITERAL(TMP393, "Compiling...", 12);
STRING_LITERAL(TMP394, "nim c -d:release --gcc.exe:$1 main.nim", 38);
STRING_LITERAL(TMP395, "i686-elf-gcc", 12);
STRING_LITERAL(TMP396, "i686-elf-as", 11);
STRING_LITERAL(TMP397, "boot.s -o boot.o", 16);
STRING_LITERAL(TMP398, "Linking...", 10);
STRING_LITERAL(TMP399, "-T linker.ld -o main.bin -ffreestanding -O2 -nostdlib boot.o ni"
"mcache/main.o nimcache/system.o nimcache/unsigned.o nimcache/iou"
"tils.o", 133);
STRING_LITERAL(TMP401, "run", 3);
STRING_LITERAL(TMP402, "Runs the operating system using QEMU.", 37);
STRING_LITERAL(TMP404, "qemu-system-i386 -kernel main.bin", 33);
TNimType NTI145248; /* object */
extern TNimType NTI108; /* int */
TNimType NTI145250; /* range -1..0(int) */
TNimType NTI145257; /* ref object */
extern orderedtable143031 tasks_143220;
extern TFrame* frameptr_16242;
TNimType NTI145307; /* object */
TNimType NTI145316; /* ref object */
TNimType NTI145346; /* object */
TNimType NTI145355; /* ref object */
N_NIMCALL(void, TMP380)(void* p, NI op) {
	TY145248* a;
	a = (TY145248*)p;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_CLOSURE(void, HEX3Aanonymous_145014)(void* ClEnv) {
	TY145248* HEX3Aenvp_145254;
	nimfr(":anonymous", "nake.nim")
	HEX3Aenvp_145254 = (TY145248*) ClEnv;
	nimln(9, "nakefile.nim");
	nosremoveFile(((NimStringDesc*) &TMP384));
	nimln(10, "nakefile.nim");
	nosremoveFile(((NimStringDesc*) &TMP385));
	nimln(11, "nakefile.nim");
	nosremoveDir(((NimStringDesc*) &TMP388));
	nimln(12, "nakefile.nim");
	nimln(12, "nakefile.nim");
	printf("%s\012", (((NimStringDesc*) &TMP389))->data);
	popFrame();
}
N_NIMCALL(void, TMP390)(void* p, NI op) {
	TY145307* a;
	a = (TY145307*)p;
}

N_CLOSURE(void, HEX3Aanonymous_145260)(void* ClEnv) {
	TY145307* HEX3Aenvp_145313;
	TY96973 LOC1;
	NIM_BOOL LOC2;
	TY143461 LOC3;
	NIM_BOOL LOC4;
	TY143461 LOC5;
	NIM_BOOL LOC6;
	nimfr(":anonymous", "nake.nim")
	HEX3Aenvp_145313 = (TY145307*) ClEnv;
	nimln(15, "nakefile.nim");
	nimln(15, "nakefile.nim");
	printf("%s\012", (((NimStringDesc*) &TMP393))->data);
	nimln(16, "nakefile.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	nimln(16, "nakefile.nim");
	nimln(16, "nakefile.nim");
	LOC1[0] = nsuFormatSingleElem(((NimStringDesc*) &TMP394), ((NimStringDesc*) &TMP395));
	LOC2 = 0;
	LOC2 = direshell_143398(LOC1, 1);
	nimln(18, "nakefile.nim");
	memset((void*)LOC3, 0, sizeof(LOC3));
	nimln(18, "nakefile.nim");
	LOC3[0] = copyString(((NimStringDesc*) &TMP396));
	nimln(18, "nakefile.nim");
	LOC3[1] = copyString(((NimStringDesc*) &TMP397));
	LOC4 = 0;
	LOC4 = direshell_143398(LOC3, 2);
	nimln(20, "nakefile.nim");
	nimln(20, "nakefile.nim");
	printf("%s\012", (((NimStringDesc*) &TMP398))->data);
	nimln(22, "nakefile.nim");
	memset((void*)LOC5, 0, sizeof(LOC5));
	nimln(22, "nakefile.nim");
	LOC5[0] = copyString(((NimStringDesc*) &TMP395));
	nimln(22, "nakefile.nim");
	LOC5[1] = copyString(((NimStringDesc*) &TMP399));
	LOC6 = 0;
	LOC6 = direshell_143398(LOC5, 2);
	nimln(24, "nakefile.nim");
	nimln(24, "nakefile.nim");
	printf("%s\012", (((NimStringDesc*) &TMP389))->data);
	popFrame();
}
N_NIMCALL(void, TMP400)(void* p, NI op) {
	TY145346* a;
	a = (TY145346*)p;
}

static N_INLINE(void, runtask_143249)(NimStringDesc* name) {
	ptaskHEX3Aobjecttype143013* LOC1;
	nimfr("runTask", "nake.nim")
	nimln(100, "nake.nim");
	nimln(100, "nake.nim");
	LOC1 = 0;
	LOC1 = HEX5BHEX5D_143288((&tasks_143220), name);
	(*LOC1).Action.ClEnv? (*LOC1).Action.ClPrc((*LOC1).Action.ClEnv):((TMP403)((*LOC1).Action.ClPrc))();
	popFrame();
}

N_CLOSURE(void, HEX3Aanonymous_145319)(void* ClEnv) {
	TY145346* HEX3Aenvp_145352;
	TY96973 LOC6;
	NIM_BOOL LOC7;
	nimfr(":anonymous", "nake.nim")
	HEX3Aenvp_145352 = (TY145346*) ClEnv;
	nimln(27, "nakefile.nim");
	{
		NIM_BOOL LOC3;
		nimln(27, "nakefile.nim");
		nimln(27, "nakefile.nim");
		LOC3 = 0;
		LOC3 = nosexistsFile(((NimStringDesc*) &TMP385));
		if (!!(LOC3)) goto LA4;
		nimln(27, "nakefile.nim");
		runtask_143249(((NimStringDesc*) &TMP391));
	}
	LA4: ;
	nimln(28, "nakefile.nim");
	memset((void*)LOC6, 0, sizeof(LOC6));
	nimln(28, "nakefile.nim");
	LOC6[0] = copyString(((NimStringDesc*) &TMP404));
	LOC7 = 0;
	LOC7 = direshell_143398(LOC6, 1);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	HEX00_parseutilsDatInit();
	HEX00_strutilsDatInit();
	HEX00_timesDatInit();
	HEX00_posixDatInit();
	HEX00_osDatInit();
	HEX00_parseoptDatInit();
	HEX00_hashesDatInit();
	HEX00_mathDatInit();
	HEX00_tablesDatInit();
	HEX00_rltypedefsDatInit();
	HEX00_readlineDatInit();
	HEX00_historyDatInit();
	HEX00_rdstdinDatInit();
	nake_nakeDatInit();
	nakefileDatInit();
	HEX00_parseutilsInit();
	HEX00_strutilsInit();
	HEX00_timesInit();
	HEX00_posixInit();
	HEX00_osInit();
	HEX00_parseoptInit();
	HEX00_hashesInit();
	HEX00_mathInit();
	HEX00_tablesInit();
	HEX00_rltypedefsInit();
	HEX00_readlineInit();
	HEX00_historyInit();
	HEX00_rdstdinInit();
	nake_nakeInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	nakefileInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, nakefileInit)(void) {
	TY145248* HEX3Aenv_145256;
	ttaskfunction143010 LOC1;
	ptaskHEX3Aobjecttype143013* LOC2;
	TY145307* HEX3Aenv_145315;
	ttaskfunction143010 LOC3;
	ptaskHEX3Aobjecttype143013* LOC4;
	TY145346* HEX3Aenv_145354;
	ttaskfunction143010 LOC5;
	ptaskHEX3Aobjecttype143013* LOC6;
	nimfr("nakefile", "nakefile.nim")
	HEX3Aenv_145256 = 0;
	nimln(172, "system.nim");
	HEX3Aenv_145256 = (TY145248*) newObj((&NTI145257), sizeof(TY145248));
	nimln(116, "nake.nim");
	nimln(116, "nake.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = HEX3Aanonymous_145014; LOC1.ClEnv = HEX3Aenv_145256;
	LOC2 = 0;
	LOC2 = newtask_143242(((NimStringDesc*) &TMP383), LOC1);
	HEX5BHEX5DHEX3D_145024((&tasks_143220), ((NimStringDesc*) &TMP382), LOC2);
	HEX3Aenv_145315 = 0;
	nimln(172, "system.nim");
	HEX3Aenv_145315 = (TY145307*) newObj((&NTI145316), sizeof(TY145307));
	nimln(116, "nake.nim");
	nimln(116, "nake.nim");
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	LOC3.ClPrc = HEX3Aanonymous_145260; LOC3.ClEnv = HEX3Aenv_145315;
	LOC4 = 0;
	LOC4 = newtask_143242(((NimStringDesc*) &TMP392), LOC3);
	HEX5BHEX5DHEX3D_145024((&tasks_143220), ((NimStringDesc*) &TMP391), LOC4);
	HEX3Aenv_145354 = 0;
	nimln(172, "system.nim");
	HEX3Aenv_145354 = (TY145346*) newObj((&NTI145355), sizeof(TY145346));
	nimln(116, "nake.nim");
	nimln(116, "nake.nim");
	memset((void*)(&LOC5), 0, sizeof(LOC5));
	LOC5.ClPrc = HEX3Aanonymous_145319; LOC5.ClEnv = HEX3Aenv_145354;
	LOC6 = 0;
	LOC6 = newtask_143242(((NimStringDesc*) &TMP402), LOC5);
	HEX5BHEX5DHEX3D_145024((&tasks_143220), ((NimStringDesc*) &TMP401), LOC6);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nakefileDatInit)(void) {
static TNimNode TMP129[3];
NTI145248.size = sizeof(TY145248);
NTI145248.kind = 18;
NTI145248.base = 0;
NTI145248.flags = 3;
NTI145250.size = sizeof(NI);
NTI145250.kind = 20;
NTI145250.base = (&NTI108);
NTI145250.flags = 3;
TMP129[0].kind = 1;
TMP129[0].offset = offsetof(TY145248, HEX3Astate);
TMP129[0].typ = (&NTI145250);
TMP129[0].name = ":state";
NTI145248.node = &TMP129[0];
NTI145257.size = sizeof(TY145248*);
NTI145257.kind = 22;
NTI145257.base = (&NTI145248);
NTI145257.flags = 2;
NTI145257.marker = TMP380;
NTI145307.size = sizeof(TY145307);
NTI145307.kind = 18;
NTI145307.base = 0;
NTI145307.flags = 3;
TMP129[1].kind = 1;
TMP129[1].offset = offsetof(TY145307, HEX3Astate);
TMP129[1].typ = (&NTI145250);
TMP129[1].name = ":state";
NTI145307.node = &TMP129[1];
NTI145316.size = sizeof(TY145307*);
NTI145316.kind = 22;
NTI145316.base = (&NTI145307);
NTI145316.flags = 2;
NTI145316.marker = TMP390;
NTI145346.size = sizeof(TY145346);
NTI145346.kind = 18;
NTI145346.base = 0;
NTI145346.flags = 3;
TMP129[2].kind = 1;
TMP129[2].offset = offsetof(TY145346, HEX3Astate);
TMP129[2].typ = (&NTI145250);
TMP129[2].name = ":state";
NTI145346.node = &TMP129[2];
NTI145355.size = sizeof(TY145346*);
NTI145355.kind = 22;
NTI145355.base = (&NTI145346);
NTI145355.flags = 2;
NTI145355.marker = TMP400;
}

