/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/nake_nake.o /home/chronize/Documents/projects/nimkernel/nimcache/nake_nake.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdlib.h>

#include <unistd.h>

#include <stdio.h>

#include <string.h>

#include <setjmp.h>

#include <sys/time.h>
typedef struct orderedtable143031 orderedtable143031;
typedef struct orderedkeyvaluepairseq143034 orderedkeyvaluepairseq143034;
typedef struct orderedkeyvaluepair143037 orderedkeyvaluepair143037;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct ptaskHEX3Aobjecttype143013 ptaskHEX3Aobjecttype143013;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY143227 TY143227;
typedef struct TY143230 TY143230;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct optparser127007 optparser127007;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct orderedkeyvaluepair143037 {
NU8 Field0;
NI Field1;
NimStringDesc* Field2;
ptaskHEX3Aobjecttype143013* Field3;
};
struct  orderedtable143031  {
orderedkeyvaluepairseq143034* Data;
NI Counter;
NI First;
NI Last;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} ttaskfunction143010;
struct  ptaskHEX3Aobjecttype143013  {
NimStringDesc* Desc;
ttaskfunction143010 Action;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY143227 {
void* Field0;
TY143230* Field1;
};
struct TY143230 {
char dummy;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef N_CLOSURE_PTR(void, TMP325) (void);
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY14809;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY14809 raiseAction;
};
typedef NimStringDesc* TY143461[2];
typedef NimStringDesc* TY143465[5];
typedef N_CLOSURE_PTR(void, TMP365) (void* ClEnv);
struct  optparser127007  {
  TNimObject Sup;
NimStringDesc* Cmd;
NI Pos;
NIM_BOOL Inshortstate;
NU8 Kind;
NimStringDesc* Key;
NimStringDesc* Val;
};
typedef N_CLOSURE_PTR(void, TMP379) (void);
typedef NI TY26620[8];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct orderedkeyvaluepairseq143034 {
  TGenericSeq Sup;
  orderedkeyvaluepair143037 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, initorderedtable_143023)(NI initialsize_143028, orderedtable143031* Result);
N_NIMCALL(void, TMP311)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP312)(void* p, NI op);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(NimStringDesc*, findexe_125410)(NimStringDesc* exe);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(ptaskHEX3Aobjecttype143013*, newtask_143242)(NimStringDesc* desc, ttaskfunction143010 action);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51225)(tcell45135* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c);
static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c);
N_NOINLINE(void, incl_45871)(tcellset45147* s, tcell45135* cell);
static N_INLINE(void, decref_50804)(tcell45135* c);
N_NIMCALL(ptaskHEX3Aobjecttype143013*, HEX5BHEX5D_143288)(orderedtable143031* t_143295, NimStringDesc* key_143298);
N_NIMCALL(NI, rawget_143302)(orderedtable143031* t_143309, NimStringDesc* key_143312);
static N_INLINE(void, runtask_143249)(NimStringDesc* name);
N_NIMCALL(NIM_BOOL, askshellcmd_143362)(NimStringDesc* cmd);
N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, readlinefromstdin_142001)(NimStringDesc* prompt);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, nosexecShellCmd)(NimStringDesc* command);
N_NIMCALL(NIM_BOOL, shell_143255)(NimStringDesc** cmd, NI cmdLen0);
N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen0, NimStringDesc* sep);
N_NIMCALL(NIM_BOOL, direshell_143398)(NimStringDesc** cmd, NI cmdLen0);
static N_INLINE(void, cd_143262)(NimStringDesc* dir);
static N_INLINE(void, setcurrentdir_117007)(NimStringDesc* newdir);
N_NIMCALL(void, raiseoserror_114809)(NI32 errorcode);
N_NIMCALL(NI32, oslasterror_114841)(void);
N_NIMCALL(void, mainexecution_143426)(void);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, nosgetCurrentDir)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, paramcount_123639)(void);
N_NIMCALL(NimStringDesc*, paramstr_123609)(NI i);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NU16, nosgetFilePermissions)(NimStringDesc* filename);
N_NIMCALL(NF, toseconds_101290)(time_t time);
N_NIMCALL(time_t, nosgetLastModificationTime)(NimStringDesc* file);
N_NIMCALL(NimStringDesc*, HEX2F_117299)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NIM_BOOL, needsrefresh_143488)(NimStringDesc* target, NimStringDesc** src, NI srcLen0);
N_NIMCALL(void, failedassertimpl_85225)(NimStringDesc* msg);
static N_INLINE(NI, len_143647)(orderedtable143031* t_143654);
N_NIMCALL(void, listtasksimpl_143643)(void);
N_NIMCALL(NIM_BOOL, haskey_143914)(orderedtable143031* t_143921, NimStringDesc* key_143924);
N_NOCONV(void, modulehook_143901)(void);
N_NIMCALL(void, initoptparser_127026)(NimStringDesc* cmdline, optparser127007* Result);
N_NIMCALL(void, nponext)(optparser127007* p);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
STRING_LITERAL(TMP323, "nim", 3);
STRING_LITERAL(TMP324, "nimrod", 6);
STRING_LITERAL(TMP345, "Run? `$#` [N/y]\012", 16);
STRING_LITERAL(TMP349, " ", 1);
STRING_LITERAL(TMP352, "nakefile.nim", 12);
STRING_LITERAL(TMP353, "No nakefile.nim found. Current working dir is ", 46);
STRING_LITERAL(TMP354, "", 0);
STRING_LITERAL(TMP356, "nakefile", 8);
STRING_LITERAL(TMP357, ".", 1);
STRING_LITERAL(TMP358, "c", 1);
STRING_LITERAL(TMP359, "-r", 2);
STRING_LITERAL(TMP360, "len(src) > 0 Pass some parameters to check for", 46);
STRING_LITERAL(TMP362, "tasks.len > 0 ", 14);
STRING_LITERAL(TMP363, "Available tasks:", 16);
STRING_LITERAL(TMP364, " - ", 3);
STRING_LITERAL(TMP370, "careful", 7);
STRING_LITERAL(TMP371, "tasks", 5);
STRING_LITERAL(TMP372, "t", 1);
STRING_LITERAL(TMP373, "Unknown option: ", 16);
STRING_LITERAL(TMP374, ": ", 2);
STRING_LITERAL(TMP375, "default", 7);
STRING_LITERAL(TMP376, "No task specified, running default task defined by nakefile.", 60);
STRING_LITERAL(TMP377, "Task \'", 6);
STRING_LITERAL(TMP378, "\' not found.", 12);
TNimType NTI143013; /* PTask:ObjectType */
extern TNimType NTI149; /* string */
TNimType NTI143010; /* tuple[pointer, ref tuple[]] */
extern TNimType NTI153; /* pointer */
TNimType NTI143230; /* tuple[] */
TNimType NTI143229; /* ref tuple[] */
TNimType NTI143008; /* PTask */
orderedtable143031 tasks_143220;
extern TNimType NTI143031; /* OrderedTable */
NIM_BOOL careful_143221;
NimStringDesc* nimexe_143222;
extern TFrame* frameptr_16242;
extern tgcheap47216 gch_47244;
extern TSafePoint* exchandler_16243;
extern TNimType NTI3233; /* OSError */
extern Exception* currexception_16245;
ttaskfunction143010 listtasks_143884;
extern TNimType NTI127007; /* OptParser */
N_NIMCALL(void, TMP311)(void* p, NI op) {
	TY143230* a;
	a = (TY143230*)p;
}
N_NIMCALL(void, TMP312)(void* p, NI op) {
	ptaskHEX3Aobjecttype143013* a;
	a = (ptaskHEX3Aobjecttype143013*)p;
	nimGCvisit((void*)(*a).Desc, op);
	nimGCvisit((void*)(*a).Action.ClEnv, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45135* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48846(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50404(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45871((&gch_47244.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51225)(tcell45135* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48867(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_50804)(tcell45135* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50404(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48867(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45135* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48846(src);
		incref_51225(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45135* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48846((*dest));
		decref_50804(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(ptaskHEX3Aobjecttype143013*, newtask_143242)(NimStringDesc* desc, ttaskfunction143010 action) {
	ptaskHEX3Aobjecttype143013* result;
	ptaskHEX3Aobjecttype143013* LOC1;
	NimStringDesc* LOC2;
	nimfr("newTask", "nake.nim")
	result = 0;
	nimln(98, "nake.nim");
	LOC1 = 0;
	LOC1 = (ptaskHEX3Aobjecttype143013*) newObj((&NTI143008), sizeof(ptaskHEX3Aobjecttype143013));
	LOC2 = 0;
	LOC2 = (*LOC1).Desc; (*LOC1).Desc = copyStringRC1(desc);
	if (LOC2) nimGCunrefNoCycle(LOC2);
	asgnRef((void**) (&(*LOC1).Action.ClEnv), action.ClEnv);
	(*LOC1).Action.ClPrc = action.ClPrc;
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(void, runtask_143249)(NimStringDesc* name) {
	ptaskHEX3Aobjecttype143013* LOC1;
	nimfr("runTask", "nake.nim")
	nimln(100, "nake.nim");
	nimln(100, "nake.nim");
	LOC1 = 0;
	LOC1 = HEX5BHEX5D_143288((&tasks_143220), name);
	(*LOC1).Action.ClEnv? (*LOC1).Action.ClPrc((*LOC1).Action.ClEnv):((TMP325)((*LOC1).Action.ClPrc))();
	popFrame();
}

N_NIMCALL(NIM_BOOL, askshellcmd_143362)(NimStringDesc* cmd) {
	NIM_BOOL result;
	nimfr("askShellCMD", "nake.nim")
	result = 0;
	nimln(120, "nake.nim");
	{
		NimStringDesc* ans;
		NimStringDesc* LOC5;
		NimStringDesc* LOC6;
		if (!careful_143221) goto LA3;
		nimln(121, "nake.nim");
		nimln(121, "nake.nim");
		nimln(121, "nake.nim");
		LOC5 = 0;
		LOC5 = nsuFormatSingleElem(((NimStringDesc*) &TMP345), cmd);
		LOC6 = 0;
		LOC6 = readlinefromstdin_142001(LOC5);
		ans = nsuToLowerStr(LOC6);
		nimln(122, "nake.nim");
		{
			NI LOC11;
			nimln(122, "nake.nim");
			if ((NU)(0) > (NU)(ans->Sup.len)) raiseIndexError();
			if (!(((NU8)(ans->data[0])) == ((NU8)(121)) || ((NU8)(ans->data[0])) == ((NU8)(89)))) goto LA9;
			nimln(123, "nake.nim");
			nimln(123, "nake.nim");
			nimln(123, "nake.nim");
			LOC11 = 0;
			LOC11 = nosexecShellCmd(cmd);
			result = (LOC11 == 0);
		}
		goto LA7;
		LA9: ;
		{
			nimln(124, "nake.nim");
			nimln(124, "nake.nim");
			result = NIM_FALSE;
			goto BeforeRet;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		NI LOC14;
		nimln(126, "nake.nim");
		nimln(126, "nake.nim");
		nimln(126, "nake.nim");
		LOC14 = 0;
		LOC14 = nosexecShellCmd(cmd);
		result = (LOC14 == 0);
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, shell_143255)(NimStringDesc** cmd, NI cmdLen0) {
	NIM_BOOL result;
	NimStringDesc* LOC1;
	nimfr("shell", "nake.nim")
	result = 0;
	nimln(129, "nake.nim");
	nimln(129, "nake.nim");
	LOC1 = 0;
	LOC1 = nsuJoinSep(cmd, cmdLen0, ((NimStringDesc*) &TMP349));
	result = askshellcmd_143362(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, direshell_143398)(NimStringDesc** cmd, NI cmdLen0) {
	NIM_BOOL result;
	nimfr("direShell", "nake.nim")
	result = 0;
	nimln(132, "nake.nim");
	result = shell_143255(cmd, cmdLen0);
	nimln(133, "nake.nim");
	{
		nimln(133, "nake.nim");
		if (!!(result)) goto LA3;
		nimln(133, "nake.nim");
		exit(1);
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(void, setcurrentdir_117007)(NimStringDesc* newdir) {
	nimfr("setCurrentDir", "os.nim")
	nimln(514, "os.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(514, "os.nim");
		nimln(514, "os.nim");
		nimln(514, "os.nim");
		LOC3 = 0;
		LOC3 = chdir(newdir->data);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		nimln(514, "os.nim");
		nimln(514, "os.nim");
		LOC6 = 0;
		LOC6 = oslasterror_114841();
		raiseoserror_114809(LOC6);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, cd_143262)(NimStringDesc* dir) {
	nimfr("cd", "nake.nim")
	nimln(135, "nake.nim");
	setcurrentdir_117007(dir);
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_16243;
	exchandler_16243 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_16243 = (*exchandler_16243).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_16242 = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2619, "system.nim");
	result = currexception_16245;
	popFrame();
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_16245), (*currexception_16245).parent);
}

N_NIMCALL(void, mainexecution_143426)(void) {
	NimStringDesc* args;
	TSafePoint TMP355;
	NI LOC33;
	nimfr("mainExecution", "nake.nim")
	nimln(155, "nake.nim");
	{
		NIM_BOOL LOC3;
		NimStringDesc* LOC6;
		nimln(155, "nake.nim");
		nimln(155, "nake.nim");
		LOC3 = 0;
		LOC3 = nosexistsFile(((NimStringDesc*) &TMP352));
		if (!!(LOC3)) goto LA4;
		nimln(156, "nake.nim");
		nimln(156, "nake.nim");
		nimln(156, "nake.nim");
		nimln(156, "nake.nim");
		LOC6 = 0;
		LOC6 = nosgetCurrentDir();
		printf("%s%s\012", (((NimStringDesc*) &TMP353))->data, (LOC6)->data);
		nimln(157, "nake.nim");
		exit(1);
	}
	LA4: ;
	nimln(158, "nake.nim");
	args = copyString(((NimStringDesc*) &TMP354));
	{
		NI i_143443;
		NI HEX3Atmp_143468;
		NI res_143471;
		i_143443 = 0;
		HEX3Atmp_143468 = 0;
		nimln(159, "nake.nim");
		HEX3Atmp_143468 = paramcount_123639();
		nimln(1576, "system.nim");
		res_143471 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				NimStringDesc* LOC10;
				nimln(1577, "system.nim");
				if (!(res_143471 <= HEX3Atmp_143468)) goto LA9;
				nimln(1576, "system.nim");
				i_143443 = res_143471;
				nimln(160, "nake.nim");
				nimln(160, "nake.nim");
				LOC10 = 0;
				LOC10 = paramstr_123609(i_143443);
				args = resizeString(args, LOC10->Sup.len + 0);
appendString(args, LOC10);
				nimln(161, "nake.nim");
				args = resizeString(args, 1);
appendString(args, ((NimStringDesc*) &TMP349));
				nimln(1579, "system.nim");
				res_143471 = addInt(res_143471, 1);
			} LA9: ;
		}
	}
	nimln(164, "nake.nim");
	pushSafePoint(&TMP355);
	TMP355.status = setjmp(TMP355.context);
	if (TMP355.status == 0) {
		nimln(165, "nake.nim");
		{
			NU16 LOC14;
			NF binarytime;
			time_t LOC17;
			NF nakefiletime;
			time_t LOC18;
			nimln(165, "nake.nim");
			nimln(165, "nake.nim");
			LOC14 = nosgetFilePermissions(((NimStringDesc*) &TMP356));
			if (!((LOC14 &(1<<((((NU8) 0))&15)))!=0)) goto LA15;
			nimln(167, "nake.nim");
			nimln(167, "nake.nim");
			LOC17 = 0;
			LOC17 = nosgetLastModificationTime(((NimStringDesc*) &TMP356));
			binarytime = toseconds_101290(LOC17);
			nimln(168, "nake.nim");
			nimln(168, "nake.nim");
			LOC18 = 0;
			LOC18 = nosgetLastModificationTime(((NimStringDesc*) &TMP352));
			nakefiletime = toseconds_101290(LOC18);
			nimln(169, "nake.nim");
			{
				NI LOC23;
				nimln(169, "nake.nim");
				if (!(nakefiletime < binarytime)) goto LA21;
				nimln(170, "nake.nim");
				LOC23 = 0;
				nimln(170, "nake.nim");
				{
					TY143461 LOC26;
					NIM_BOOL LOC27;
					nimln(170, "nake.nim");
					memset((void*)LOC26, 0, sizeof(LOC26));
					nimln(170, "nake.nim");
					nimln(170, "nake.nim");
					LOC26[0] = HEX2F_117299(((NimStringDesc*) &TMP357), ((NimStringDesc*) &TMP356));
					nimln(170, "nake.nim");
					LOC26[1] = copyString(args);
					LOC27 = 0;
					LOC27 = shell_143255(LOC26, 2);
					if (!LOC27) goto LA28;
					LOC23 = 0;
				}
				goto LA24;
				LA28: ;
				{
					LOC23 = 1;
				}
				LA24: ;
				exit(LOC23);
			}
			LA21: ;
		}
		LA15: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI3233))) {
			TMP355.status = 0;
			popCurrentException();
		}
	}
	if (TMP355.status != 0) reraiseException();
	nimln(176, "nake.nim");
	LOC33 = 0;
	nimln(176, "nake.nim");
	{
		TY143465 LOC36;
		NIM_BOOL LOC37;
		nimln(176, "nake.nim");
		memset((void*)LOC36, 0, sizeof(LOC36));
		nimln(176, "nake.nim");
		LOC36[0] = copyString(nimexe_143222);
		nimln(176, "nake.nim");
		LOC36[1] = copyString(((NimStringDesc*) &TMP358));
		nimln(176, "nake.nim");
		LOC36[2] = copyString(((NimStringDesc*) &TMP359));
		nimln(176, "nake.nim");
		LOC36[3] = copyString(((NimStringDesc*) &TMP352));
		nimln(176, "nake.nim");
		LOC36[4] = copyString(args);
		LOC37 = 0;
		LOC37 = shell_143255(LOC36, 5);
		if (!LOC37) goto LA38;
		LOC33 = 0;
	}
	goto LA34;
	LA38: ;
	{
		LOC33 = 1;
	}
	LA34: ;
	exit(LOC33);
	popFrame();
}

N_NIMCALL(NIM_BOOL, needsrefresh_143488)(NimStringDesc* target, NimStringDesc** src, NI srcLen0) {
	NIM_BOOL result;
	NF volatile targettime;
	TSafePoint TMP361;
	nimfr("needsRefresh", "nake.nim")
	result = 0;
	nimln(198, "nake.nim");
	{
		nimln(198, "nake.nim");
		nimln(198, "nake.nim");
		nimln(198, "nake.nim");
		if (!!((0 < srcLen0))) goto LA3;
		nimln(198, "nake.nim");
		failedassertimpl_85225(((NimStringDesc*) &TMP360));
	}
	LA3: ;
	targettime = 0;
	nimln(200, "nake.nim");
	pushSafePoint(&TMP361);
	TMP361.status = setjmp(TMP361.context);
	if (TMP361.status == 0) {
		time_t LOC6;
		nimln(201, "nake.nim");
		nimln(201, "nake.nim");
		LOC6 = 0;
		LOC6 = nosgetLastModificationTime(target);
		targettime = toseconds_101290(LOC6);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI3233))) {
			TMP361.status = 0;
			nimln(203, "nake.nim");
			nimln(203, "nake.nim");
			result = NIM_TRUE;
			popCurrentException();
			goto BeforeRet;
			popCurrentException();
		}
	}
	if (TMP361.status != 0) reraiseException();
	{
		NimStringDesc* s_143621;
		NI i_143627;
		s_143621 = 0;
		nimln(1649, "system.nim");
		i_143627 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				NF srctime;
				time_t LOC12;
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_143627 < srcLen0)) goto LA11;
				nimln(1651, "system.nim");
				if ((NU)(i_143627) >= (NU)(srcLen0)) raiseIndexError();
				s_143621 = src[i_143627];
				nimln(206, "nake.nim");
				nimln(206, "nake.nim");
				LOC12 = 0;
				LOC12 = nosgetLastModificationTime(s_143621);
				srctime = toseconds_101290(LOC12);
				nimln(207, "nake.nim");
				{
					nimln(207, "nake.nim");
					if (!(targettime < srctime)) goto LA15;
					nimln(208, "nake.nim");
					nimln(208, "nake.nim");
					result = NIM_TRUE;
					goto BeforeRet;
				}
				LA15: ;
				nimln(1652, "system.nim");
				i_143627 = addInt(i_143627, 1);
			} LA11: ;
		}
	}
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, len_143647)(orderedtable143031* t_143654) {
	NI result;
	nimfr("len", "tables.nim")
	result = 0;
	nimln(374, "tables.nim");
	result = (*t_143654).Counter;
	popFrame();
	return result;
}

N_NIMCALL(void, listtasksimpl_143643)(void) {
	nimfr("listTasksImpl", "nake.nim")
	nimln(217, "nake.nim");
	{
		NI LOC3;
		nimln(217, "nake.nim");
		nimln(217, "nake.nim");
		nimln(217, "nake.nim");
		LOC3 = 0;
		LOC3 = len_143647((&tasks_143220));
		if (!!((0 < LOC3))) goto LA4;
		nimln(217, "nake.nim");
		failedassertimpl_85225(((NimStringDesc*) &TMP362));
	}
	LA4: ;
	nimln(218, "nake.nim");
	nimln(218, "nake.nim");
	printf("%s\012", (((NimStringDesc*) &TMP363))->data);
	{
		NimStringDesc* name_143857;
		ptaskHEX3Aobjecttype143013* task_143858;
		NI h_143866;
		name_143857 = 0;
		task_143858 = 0;
		nimln(377, "tables.nim");
		h_143866 = tasks_143220.First;
		{
			nimln(378, "tables.nim");
			while (1) {
				NI nxt_143868;
				nimln(378, "tables.nim");
				if (!(0 <= h_143866)) goto LA8;
				nimln(379, "tables.nim");
				if ((NU)(h_143866) >= (NU)(tasks_143220.Data->Sup.len)) raiseIndexError();
				nxt_143868 = tasks_143220.Data->data[h_143866].Field1;
				nimln(380, "tables.nim");
				{
					nimln(380, "tables.nim");
					if ((NU)(h_143866) >= (NU)(tasks_143220.Data->Sup.len)) raiseIndexError();
					if (!(tasks_143220.Data->data[h_143866].Field0 == ((NU8) 1))) goto LA11;
					nimln(387, "tables.nim");
					if ((NU)(h_143866) >= (NU)(tasks_143220.Data->Sup.len)) raiseIndexError();
					name_143857 = tasks_143220.Data->data[h_143866].Field2;
					nimln(387, "tables.nim");
					if ((NU)(h_143866) >= (NU)(tasks_143220.Data->Sup.len)) raiseIndexError();
					task_143858 = tasks_143220.Data->data[h_143866].Field3;
					nimln(220, "nake.nim");
					nimln(220, "nake.nim");
					nimln(220, "nake.nim");
					nimln(220, "nake.nim");
					printf("%s%s%s\012", (name_143857)->data, (((NimStringDesc*) &TMP364))->data, ((*task_143858).Desc)->data);
				}
				LA11: ;
				nimln(381, "tables.nim");
				h_143866 = nxt_143868;
			} LA8: ;
		}
	}
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NOCONV(void, modulehook_143901)(void) {
	NimStringDesc* task;
	NIM_BOOL printtasklist;
	NIM_BOOL badtask;
	NIM_BOOL LOC19;
	NIM_BOOL LOC21;
	nimfr("moduleHook", "nake.nim")
	task = 0;
	printtasklist = 0;
	{
		NU8 kind_143905;
		NimStringDesc* key_143906;
		NimStringDesc* val_143907;
		optparser127007 p_143971;
		kind_143905 = 0;
		key_143906 = 0;
		val_143907 = 0;
		memset((void*)(&p_143971), 0, sizeof(p_143971));
		p_143971.Sup.m_type = (&NTI127007);
		nimln(150, "parseopt.nim");
		chckNil((void*)(&p_143971));
		memset((void*)(&p_143971), 0, sizeof(p_143971));
		p_143971.Sup.m_type = (&NTI127007);
		initoptparser_127026(((NimStringDesc*) &TMP354), (&p_143971));
		{
			nimln(151, "parseopt.nim");
			while (1) {
				nimln(152, "parseopt.nim");
				nponext((&p_143971));
				nimln(153, "parseopt.nim");
				{
					nimln(153, "parseopt.nim");
					if (!(p_143971.Kind == ((NU8) 0))) goto LA6;
					nimln(153, "parseopt.nim");
					goto LA2;
				}
				LA6: ;
				nimln(154, "parseopt.nim");
				kind_143905 = p_143971.Kind;
				nimln(154, "parseopt.nim");
				key_143906 = p_143971.Key;
				nimln(154, "parseopt.nim");
				val_143907 = p_143971.Val;
				nimln(264, "nake.nim");
				switch (kind_143905) {
				case ((NU8) 2):
				case ((NU8) 3):
				{
					NimStringDesc* LOC9;
					nimln(266, "nake.nim");
					nimln(266, "nake.nim");
					LOC9 = 0;
					LOC9 = nsuToLowerStr(key_143906);
					if (eqStrings(LOC9, ((NimStringDesc*) &TMP370))) goto LA10;
					if (eqStrings(LOC9, ((NimStringDesc*) &TMP358))) goto LA10;
					if (eqStrings(LOC9, ((NimStringDesc*) &TMP371))) goto LA11;
					if (eqStrings(LOC9, ((NimStringDesc*) &TMP372))) goto LA11;
					goto LA12;
					LA10: ;
					{
						nimln(268, "nake.nim");
						careful_143221 = NIM_TRUE;
					}
					goto LA13;
					LA11: ;
					{
						nimln(270, "nake.nim");
						printtasklist = NIM_TRUE;
					}
					goto LA13;
					LA12: ;
					{
						nimln(272, "nake.nim");
						nimln(272, "nake.nim");
						nimln(272, "nake.nim");
						nimln(272, "nake.nim");
						nimln(272, "nake.nim");
						printf("%s%s%s%s\012", (((NimStringDesc*) &TMP373))->data, (key_143906)->data, (((NimStringDesc*) &TMP374))->data, (val_143907)->data);
					}
					LA13: ;
				}
				break;
				case ((NU8) 1):
				{
					nimln(274, "nake.nim");
					task = copyString(key_143906);
				}
				break;
				default:
				{
				}
				break;
				}
			}
		} LA2: ;
	}
	nimln(277, "nake.nim");
	nimln(277, "nake.nim");
	LOC19 = 0;
	nimln(277, "nake.nim");
	nimln(277, "nake.nim");
	LOC19 = !(task == 0);
	if (!(LOC19)) goto LA20;
	nimln(277, "nake.nim");
	nimln(277, "nake.nim");
	LOC21 = 0;
	LOC21 = haskey_143914((&tasks_143220), task);
	LOC19 = !(LOC21);
	LA20: ;
	badtask = LOC19;
	nimln(278, "nake.nim");
	{
		NIM_BOOL LOC24;
		nimln(278, "nake.nim");
		LOC24 = 0;
		nimln(278, "nake.nim");
		LOC24 = task == 0;
		if (!(LOC24)) goto LA25;
		nimln(278, "nake.nim");
		LOC24 = haskey_143914((&tasks_143220), ((NimStringDesc*) &TMP375));
		LA25: ;
		if (!LOC24) goto LA26;
		nimln(279, "nake.nim");
		nimln(279, "nake.nim");
		printf("%s\012", (((NimStringDesc*) &TMP376))->data);
		nimln(280, "nake.nim");
		task = copyString(((NimStringDesc*) &TMP375));
	}
	LA26: ;
	nimln(281, "nake.nim");
	{
		NIM_BOOL LOC30;
		NIM_BOOL LOC31;
		NI LOC41;
		nimln(281, "nake.nim");
		LOC30 = 0;
		nimln(281, "nake.nim");
		LOC31 = 0;
		LOC31 = printtasklist;
		if (LOC31) goto LA32;
		nimln(281, "nake.nim");
		LOC31 = task == 0;
		LA32: ;
		LOC30 = LOC31;
		if (LOC30) goto LA33;
		LOC30 = badtask;
		LA33: ;
		if (!LOC30) goto LA34;
		nimln(282, "nake.nim");
		{
			NimStringDesc* LOC40;
			if (!badtask) goto LA38;
			nimln(282, "nake.nim");
			nimln(282, "nake.nim");
			nimln(282, "nake.nim");
			LOC40 = 0;
			LOC40 = rawNewString(task->Sup.len + 18);
appendString(LOC40, ((NimStringDesc*) &TMP377));
appendString(LOC40, task);
appendString(LOC40, ((NimStringDesc*) &TMP378));
			printf("%s\012", (LOC40)->data);
		}
		LA38: ;
		nimln(283, "nake.nim");
		listtasks_143884.ClEnv? listtasks_143884.ClPrc(listtasks_143884.ClEnv):((TMP379)(listtasks_143884.ClPrc))();
		nimln(284, "nake.nim");
		LOC41 = 0;
		nimln(284, "nake.nim");
		{
			if (!badtask) goto LA44;
			LOC41 = 1;
		}
		goto LA42;
		LA44: ;
		{
			LOC41 = 0;
		}
		LA42: ;
		exit(LOC41);
	}
	LA34: ;
	nimln(285, "nake.nim");
	runtask_143249(task);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, nake_nakeInit)(void) {
	ttaskfunction143010 LOC5;
	nimfr("nake", "nake.nim")
	nimln(33, "nake.nim");
	chckNil((void*)(&tasks_143220));
	genericReset((void*)(&tasks_143220), (&NTI143031));
	initorderedtable_143023(32, (&tasks_143220));
	nimln(38, "nake.nim");
	careful_143221 = NIM_FALSE;
	nimln(52, "nake.nim");
	asgnRefNoCycle((void**) (&nimexe_143222), findexe_125410(((NimStringDesc*) &TMP323)));
	nimln(53, "nake.nim");
	{
		nimln(53, "nake.nim");
		nimln(53, "nake.nim");
		if (!(nimexe_143222->Sup.len < 1)) goto LA3;
		nimln(54, "nake.nim");
		asgnRefNoCycle((void**) (&nimexe_143222), findexe_125410(((NimStringDesc*) &TMP324)));
	}
	LA3: ;
	nimln(223, "nake.nim");
	memset((void*)(&LOC5), 0, sizeof(LOC5));
	LOC5.ClPrc = ((TMP365) (listtasksimpl_143643)); LOC5.ClEnv = NIM_NIL;
	asgnRef((void**) (&listtasks_143884.ClEnv), LOC5.ClEnv);
	listtasks_143884.ClPrc = LOC5.ClPrc;
	nimln(290, "nake.nim");
	atexit(modulehook_143901);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nake_nakeDatInit)(void) {
static TNimNode* TMP309[2];
static TNimNode* TMP310[2];
static TNimNode TMP131[7];
NTI143013.size = sizeof(ptaskHEX3Aobjecttype143013);
NTI143013.kind = 18;
NTI143013.base = 0;
TMP309[0] = &TMP131[1];
TMP131[1].kind = 1;
TMP131[1].offset = offsetof(ptaskHEX3Aobjecttype143013, Desc);
TMP131[1].typ = (&NTI149);
TMP131[1].name = "desc";
TMP309[1] = &TMP131[2];
NTI143010.size = sizeof(TY143227);
NTI143010.kind = 18;
NTI143010.base = 0;
NTI143010.flags = 2;
TMP310[0] = &TMP131[4];
TMP131[4].kind = 1;
TMP131[4].offset = offsetof(TY143227, Field0);
TMP131[4].typ = (&NTI153);
TMP131[4].name = "Field0";
TMP310[1] = &TMP131[5];
NTI143230.size = sizeof(TY143230);
NTI143230.kind = 18;
NTI143230.base = 0;
NTI143230.flags = 3;
TMP131[6].len = 0; TMP131[6].kind = 2;
NTI143230.node = &TMP131[6];
NTI143229.size = sizeof(TY143230*);
NTI143229.kind = 22;
NTI143229.base = (&NTI143230);
NTI143229.flags = 2;
NTI143229.marker = TMP311;
TMP131[5].kind = 1;
TMP131[5].offset = offsetof(TY143227, Field1);
TMP131[5].typ = (&NTI143229);
TMP131[5].name = "Field1";
TMP131[3].len = 2; TMP131[3].kind = 2; TMP131[3].sons = &TMP310[0];
NTI143010.node = &TMP131[3];
TMP131[2].kind = 1;
TMP131[2].offset = offsetof(ptaskHEX3Aobjecttype143013, Action);
TMP131[2].typ = (&NTI143010);
TMP131[2].name = "action";
TMP131[0].len = 2; TMP131[0].kind = 2; TMP131[0].sons = &TMP309[0];
NTI143013.node = &TMP131[0];
NTI143008.size = sizeof(ptaskHEX3Aobjecttype143013*);
NTI143008.kind = 22;
NTI143008.base = (&NTI143013);
NTI143008.marker = TMP312;
}

