/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/os.o /home/chronize/Documents/projects/nimkernel/nimcache/os.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <sys/stat.h>

#include <sys/types.h>

#include <sys/time.h>

#include <stdlib.h>

#include <errno.h>

#include <unistd.h>

#include <stdio.h>

#include <dirent.h>
typedef struct TY13206 TY13206;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct indexerror3255 indexerror3255;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct oserror3233 oserror3233;
typedef struct systemerror3229 systemerror3229;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  indexerror3255  {
  Exception Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
struct  systemerror3229  {
  Exception Sup;
};
struct  oserror3233  {
  systemerror3229 Sup;
NI32 Errorcode;
};
typedef NIM_CHAR TY104554[256];
typedef NI TY26620[8];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct TY13206 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
static N_INLINE(NimStringDesc*, pop_121310)(TY13206** s_121318);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_NIMCALL(NI, searchextpos_117551)(NimStringDesc* s);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, normext_117541)(NimStringDesc* ext);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, getenv_120442)(NimStringDesc* key);
N_NIMCALL(NI, findenvvar_120405)(NimStringDesc* key);
N_NIMCALL(void, getenvvarsc_120002)(void);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(void, failedassertimpl_85225)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75028, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, HEX2F_117299)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NimStringDesc*, oserrormsg_114620)(NI32 errorcode);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(void, raiseoserror_114809)(NI32 errorcode);
N_NIMCALL(NI32, oslasterror_114841)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, nosremoveFile)(NimStringDesc* file);
N_NIMCALL(void, nosremoveDir)(NimStringDesc* dir);
N_NIMCALL(void, rawremovedir_121422)(NimStringDesc* dir);
STRING_LITERAL(TMP265, "invalid index", 13);
STRING_LITERAL(TMP316, "", 0);
STRING_LITERAL(TMP319, "PATH", 4);
STRING_LITERAL(TMP320, "\'\\0\' != sep ", 12);
STRING_LITERAL(TMP351, "unknown OS error", 16);
STRING_LITERAL(TMP386, ".", 1);
STRING_LITERAL(TMP387, "..", 2);
NIM_BOOL envcomputed_119807;
TY13206* environment_119809;
extern NCSTRING* environ;
extern TFrame* frameptr_16242;
extern int cmdCount;
extern NCSTRING* cmdLine;
extern TNimType NTI20801; /* ref IndexError */
extern TNimType NTI3255; /* IndexError */
extern tgcheap47216 gch_47244;
extern TNimType NTI13206; /* seq[string] */
extern TNimType NTI114812; /* ref OSError */
extern TNimType NTI3233; /* OSError */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NimStringDesc*, pop_121310)(TY13206** s_121318) {
	NimStringDesc* result;
	NI l;
	NI TMP260;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	TMP260 = subInt((*s_121318)->Sup.len, 1);
	l = (NI64)(TMP260);
	nimln(1811, "system.nim");
	if ((NU)(l) >= (NU)((*s_121318)->Sup.len)) raiseIndexError();
	result = copyString((*s_121318)->data[l]);
	nimln(1812, "system.nim");
	(*s_121318) = (TY13206*) setLengthSeq(&((*s_121318))->Sup, sizeof(NimStringDesc*), l);
	popFrame();
	return result;
}

N_NIMCALL(NI, paramcount_123639)(void) {
	NI result;
	NI TMP262;
	nimfr("paramCount", "os.nim")
	result = 0;
	nimln(1701, "os.nim");
	nimln(1701, "os.nim");
	TMP262 = subInt(cmdCount, ((NI32) 1));
	if (TMP262 < (-2147483647 -1) || TMP262 > 2147483647) raiseOverflow();
	result = ((NI) ((NI32)(TMP262)));
	popFrame();
	return result;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45135* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48846(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50404(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, paramstr_123609)(NI i) {
	NimStringDesc* result;
	indexerror3255* e_123616;
	NimStringDesc* LOC7;
	nimfr("paramStr", "os.nim")
	result = 0;
	nimln(1696, "os.nim");
	{
		NIM_BOOL LOC3;
		nimln(1696, "os.nim");
		LOC3 = 0;
		nimln(1696, "os.nim");
		LOC3 = (i < ((NI) (cmdCount)));
		if (!(LOC3)) goto LA4;
		nimln(1696, "os.nim");
		LOC3 = (0 <= i);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(1696, "os.nim");
		nimln(1696, "os.nim");
		nimln(1696, "os.nim");
		if ((NU)(i) > (NU)(50000)) raiseIndexError();
		result = cstrToNimstr(cmdLine[(i)- 0]);
		goto BeforeRet;
	}
	LA5: ;
	e_123616 = 0;
	nimln(2149, "system.nim");
	e_123616 = (indexerror3255*) newObj((&NTI20801), sizeof(indexerror3255));
	(*e_123616).Sup.Sup.m_type = (&NTI3255);
	nimln(2150, "system.nim");
	LOC7 = 0;
	LOC7 = (*e_123616).Sup.message; (*e_123616).Sup.message = copyStringRC1(((NimStringDesc*) &TMP265));
	if (LOC7) nimGCunrefNoCycle(LOC7);
	nimln(1697, "os.nim");
	raiseException((Exception*)e_123616, "IndexError");
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, searchextpos_117551)(NimStringDesc* s) {
	NI result;
	nimfr("searchExtPos", "os.nim")
	result = 0;
	nimln(666, "os.nim");
	result = -1;
	{
		NI i_117566;
		NI HEX3Atmp_117582;
		NI TMP315;
		NI res_117585;
		i_117566 = 0;
		HEX3Atmp_117582 = 0;
		nimln(667, "os.nim");
		nimln(667, "os.nim");
		nimln(667, "os.nim");
		TMP315 = subInt(s->Sup.len, 1);
		HEX3Atmp_117582 = (NI64)(TMP315);
		nimln(1560, "system.nim");
		res_117585 = HEX3Atmp_117582;
		{
			nimln(1561, "system.nim");
			while (1) {
				nimln(1561, "system.nim");
				if (!(1 <= res_117585)) goto LA3;
				nimln(1560, "system.nim");
				i_117566 = res_117585;
				nimln(668, "os.nim");
				{
					nimln(668, "os.nim");
					if ((NU)(i_117566) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NU8)(s->data[i_117566]) == (NU8)(46))) goto LA6;
					nimln(669, "os.nim");
					result = i_117566;
					nimln(670, "os.nim");
					goto LA1;
				}
				goto LA4;
				LA6: ;
				{
					nimln(671, "os.nim");
					if ((NU)(i_117566) > (NU)(s->Sup.len)) raiseIndexError();
					if (!(((NU8)(s->data[i_117566])) == ((NU8)(47)) || ((NU8)(s->data[i_117566])) == ((NU8)(47)))) goto LA9;
					nimln(672, "os.nim");
					goto LA1;
				}
				goto LA4;
				LA9: ;
				LA4: ;
				nimln(1563, "system.nim");
				res_117585 = subInt(res_117585, 1);
			} LA3: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, normext_117541)(NimStringDesc* ext) {
	NimStringDesc* result;
	nimfr("normExt", "os.nim")
	result = 0;
	nimln(661, "os.nim");
	{
		NIM_BOOL LOC3;
		nimln(661, "os.nim");
		LOC3 = 0;
		nimln(661, "os.nim");
		LOC3 = ((ext) && (ext)->Sup.len == 0);
		if (LOC3) goto LA4;
		nimln(661, "os.nim");
		if ((NU)(0) > (NU)(ext->Sup.len)) raiseIndexError();
		LOC3 = ((NU8)(ext->data[0]) == (NU8)(46));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(661, "os.nim");
		result = copyString(ext);
	}
	goto LA1;
	LA5: ;
	{
		NimStringDesc* LOC8;
		nimln(662, "os.nim");
		nimln(662, "os.nim");
		LOC8 = 0;
		LOC8 = rawNewString(ext->Sup.len + 1);
appendChar(LOC8, 46);
appendString(LOC8, ext);
		result = LOC8;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext) {
	NimStringDesc* result;
	NI extpos;
	nimfr("addFileExt", "os.nim")
	result = 0;
	nimln(762, "os.nim");
	extpos = searchextpos_117551(filename);
	nimln(763, "os.nim");
	{
		NimStringDesc* LOC5;
		NimStringDesc* LOC6;
		nimln(763, "os.nim");
		if (!(extpos < 0)) goto LA3;
		nimln(763, "os.nim");
		nimln(763, "os.nim");
		LOC5 = 0;
		nimln(763, "os.nim");
		LOC6 = 0;
		LOC6 = normext_117541(ext);
		LOC5 = rawNewString(filename->Sup.len + LOC6->Sup.len + 0);
appendString(LOC5, filename);
appendString(LOC5, LOC6);
		result = LOC5;
	}
	goto LA1;
	LA3: ;
	{
		nimln(764, "os.nim");
		result = copyString(filename);
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL LOC1;
	int LOC2;
	nimfr("existsFile", "os.nim")
	result = 0;
	memset((void*)(&res), 0, sizeof(res));
	nimln(394, "os.nim");
	nimln(394, "os.nim");
	nimln(394, "os.nim");
	LOC1 = 0;
	nimln(394, "os.nim");
	nimln(394, "os.nim");
	LOC2 = 0;
	LOC2 = stat(filename->data, (&res));
	LOC1 = (((NI32) 0) <= LOC2);
	if (!(LOC1)) goto LA3;
	nimln(394, "os.nim");
	LOC1 = S_ISREG(res.st_mode);
	LA3: ;
	result = LOC1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, getenvvarsc_120002)(void) {
	nimfr("getEnvVarsC", "os.nim")
	nimln(1130, "os.nim");
	{
		NI i;
		nimln(1130, "os.nim");
		if (!!(envcomputed_119807)) goto LA3;
		nimln(1131, "os.nim");
		if (environment_119809) nimGCunrefNoCycle(environment_119809);
		environment_119809 = (TY13206*) newSeqRC1((&NTI13206), 0);
		nimln(1134, "os.nim");
		i = 0;
		{
			nimln(1135, "os.nim");
			while (1) {
				NimStringDesc* LOC11;
				NimStringDesc* LOC12;
				nimln(1136, "os.nim");
				{
					nimln(1136, "os.nim");
					if ((NU)(i) > (NU)(50000)) raiseIndexError();
					if (!(environ[(i)- 0] == NIM_NIL)) goto LA9;
					nimln(1136, "os.nim");
					goto LA5;
				}
				LA9: ;
				nimln(1137, "os.nim");
				nimln(1137, "os.nim");
				if ((NU)(i) > (NU)(50000)) raiseIndexError();
				LOC11 = 0;
				LOC11 = cstrToNimstr(environ[(i)- 0]);
				environment_119809 = (TY13206*) incrSeq(&(environment_119809)->Sup, sizeof(NimStringDesc*));
				LOC12 = 0;
				LOC12 = environment_119809->data[environment_119809->Sup.len-1]; environment_119809->data[environment_119809->Sup.len-1] = copyStringRC1(LOC11);
				if (LOC12) nimGCunrefNoCycle(LOC12);
				nimln(1138, "os.nim");
				i = addInt(i, 1);
			}
		} LA5: ;
		nimln(1139, "os.nim");
		envcomputed_119807 = NIM_TRUE;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NI, findenvvar_120405)(NimStringDesc* key) {
	NI result;
	NimStringDesc* temp;
	NimStringDesc* LOC1;
	nimfr("findEnvVar", "os.nim")
	result = 0;
	nimln(1142, "os.nim");
	getenvvarsc_120002();
	nimln(1143, "os.nim");
	nimln(1143, "os.nim");
	LOC1 = 0;
	LOC1 = rawNewString(key->Sup.len + 1);
appendString(LOC1, key);
appendChar(LOC1, 61);
	temp = LOC1;
	{
		NI i_120420;
		NI HEX3Atmp_120422;
		NI res_120425;
		i_120420 = 0;
		HEX3Atmp_120422 = 0;
		nimln(1144, "os.nim");
		nimln(1144, "os.nim");
		HEX3Atmp_120422 = (environment_119809->Sup.len-1);
		nimln(1576, "system.nim");
		res_120425 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				nimln(1577, "system.nim");
				if (!(res_120425 <= HEX3Atmp_120422)) goto LA4;
				nimln(1576, "system.nim");
				i_120420 = res_120425;
				nimln(1145, "os.nim");
				{
					NIM_BOOL LOC7;
					nimln(1145, "os.nim");
					if ((NU)(i_120420) >= (NU)(environment_119809->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = nsuStartsWith(environment_119809->data[i_120420], temp);
					if (!LOC7) goto LA8;
					nimln(1145, "os.nim");
					nimln(1145, "os.nim");
					result = i_120420;
					goto BeforeRet;
				}
				LA8: ;
				nimln(1579, "system.nim");
				res_120425 = addInt(res_120425, 1);
			} LA4: ;
		}
	}
	nimln(1146, "os.nim");
	nimln(1146, "os.nim");
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getenv_120442)(NimStringDesc* key) {
	NimStringDesc* result;
	NI i;
	nimfr("getEnv", "os.nim")
	result = 0;
	nimln(1154, "os.nim");
	i = findenvvar_120405(key);
	nimln(1155, "os.nim");
	{
		NI LOC5;
		NI TMP318;
		nimln(1155, "os.nim");
		if (!(0 <= i)) goto LA3;
		nimln(1156, "os.nim");
		nimln(1156, "os.nim");
		nimln(1156, "os.nim");
		if ((NU)(i) >= (NU)(environment_119809->Sup.len)) raiseIndexError();
		nimln(1156, "os.nim");
		nimln(1156, "os.nim");
		if ((NU)(i) >= (NU)(environment_119809->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = nsuFindChar(environment_119809->data[i], 61, 0);
		TMP318 = addInt(LOC5, 1);
		result = copyStr(environment_119809->data[i], (NI64)(TMP318));
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		NCSTRING env;
		nimln(1158, "os.nim");
		env = getenv(key->data);
		nimln(1159, "os.nim");
		{
			nimln(1159, "os.nim");
			if (!(env == NIM_NIL)) goto LA9;
			nimln(1159, "os.nim");
			nimln(1159, "os.nim");
			result = copyString(((NimStringDesc*) &TMP316));
			goto BeforeRet;
		}
		LA9: ;
		nimln(1160, "os.nim");
		nimln(1160, "os.nim");
		result = cstrToNimstr(env);
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr("joinPath", "os.nim")
	result = 0;
	nimln(541, "os.nim");
	{
		nimln(541, "os.nim");
		nimln(541, "os.nim");
		if (!(head->Sup.len == 0)) goto LA3;
		nimln(542, "os.nim");
		result = copyString(tail);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP322;
		nimln(543, "os.nim");
		nimln(543, "os.nim");
		nimln(543, "os.nim");
		TMP322 = subInt(head->Sup.len, 1);
		if ((NU)((NI64)(TMP322)) > (NU)(head->Sup.len)) raiseIndexError();
		if (!(((NU8)(head->data[(NI64)(TMP322)])) == ((NU8)(47)) || ((NU8)(head->data[(NI64)(TMP322)])) == ((NU8)(47)))) goto LA6;
		nimln(544, "os.nim");
		{
			NimStringDesc* LOC12;
			NimStringDesc* LOC13;
			nimln(544, "os.nim");
			if ((NU)(0) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[0])) == ((NU8)(47)) || ((NU8)(tail->data[0])) == ((NU8)(47)))) goto LA10;
			nimln(545, "os.nim");
			nimln(545, "os.nim");
			LOC12 = 0;
			nimln(545, "os.nim");
			LOC13 = 0;
			LOC13 = copyStr(tail, 1);
			LOC12 = rawNewString(head->Sup.len + LOC13->Sup.len + 0);
appendString(LOC12, head);
appendString(LOC12, LOC13);
			result = LOC12;
		}
		goto LA8;
		LA10: ;
		{
			NimStringDesc* LOC15;
			nimln(547, "os.nim");
			nimln(547, "os.nim");
			LOC15 = 0;
			LOC15 = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(LOC15, head);
appendString(LOC15, tail);
			result = LOC15;
		}
		LA8: ;
	}
	goto LA1;
	LA6: ;
	{
		nimln(549, "os.nim");
		{
			NimStringDesc* LOC21;
			nimln(549, "os.nim");
			if ((NU)(0) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[0])) == ((NU8)(47)) || ((NU8)(tail->data[0])) == ((NU8)(47)))) goto LA19;
			nimln(550, "os.nim");
			nimln(550, "os.nim");
			LOC21 = 0;
			LOC21 = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(LOC21, head);
appendString(LOC21, tail);
			result = LOC21;
		}
		goto LA17;
		LA19: ;
		{
			NimStringDesc* LOC23;
			nimln(552, "os.nim");
			nimln(552, "os.nim");
			LOC23 = 0;
			LOC23 = rawNewString(head->Sup.len + tail->Sup.len + 1);
appendString(LOC23, head);
appendChar(LOC23, 47);
appendString(LOC23, tail);
			result = LOC23;
		}
		LA17: ;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX2F_117299)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr("/", "os.nim")
	result = 0;
	nimln(573, "os.nim");
	nimln(573, "os.nim");
	result = nosjoinPath(head, tail);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, findexe_125410)(NimStringDesc* exe) {
	NimStringDesc* result;
	NimStringDesc* path;
	nimfr("findExe", "os.nim")
	result = 0;
	nimln(1851, "os.nim");
	result = nosaddFileExt(exe, ((NimStringDesc*) &TMP316));
	nimln(1852, "os.nim");
	{
		NIM_BOOL LOC3;
		nimln(1852, "os.nim");
		LOC3 = 0;
		LOC3 = nosexistsFile(result);
		if (!LOC3) goto LA4;
		nimln(1852, "os.nim");
		goto BeforeRet;
	}
	LA4: ;
	nimln(1853, "os.nim");
	nimln(1853, "os.nim");
	path = getenv_120442(((NimStringDesc*) &TMP319));
	{
		NimStringDesc* candidate_125415;
		NI last_125422;
		candidate_125415 = 0;
		nimln(279, "strutils.nim");
		last_125422 = 0;
		nimln(280, "strutils.nim");
		{
			if (!NIM_FALSE) goto LA9;
			nimln(280, "strutils.nim");
			failedassertimpl_85225(((NimStringDesc*) &TMP320));
		}
		LA9: ;
		nimln(281, "strutils.nim");
		{
			nimln(281, "strutils.nim");
			nimln(281, "strutils.nim");
			if (!(0 < path->Sup.len)) goto LA13;
			{
				nimln(283, "strutils.nim");
				while (1) {
					NI first_125424;
					NI TMP321;
					NimStringDesc* x;
					nimln(283, "strutils.nim");
					nimln(283, "strutils.nim");
					if (!(last_125422 <= path->Sup.len)) goto LA16;
					nimln(284, "strutils.nim");
					first_125424 = last_125422;
					{
						nimln(285, "strutils.nim");
						while (1) {
							NIM_BOOL LOC19;
							nimln(285, "strutils.nim");
							LOC19 = 0;
							nimln(285, "strutils.nim");
							nimln(285, "strutils.nim");
							LOC19 = (last_125422 < path->Sup.len);
							if (!(LOC19)) goto LA20;
							nimln(285, "strutils.nim");
							nimln(285, "strutils.nim");
							if ((NU)(last_125422) > (NU)(path->Sup.len)) raiseIndexError();
							LOC19 = !(((NU8)(path->data[last_125422]) == (NU8)(58)));
							LA20: ;
							if (!LOC19) goto LA18;
							nimln(285, "strutils.nim");
							last_125422 = addInt(last_125422, 1);
						} LA18: ;
					}
					nimln(286, "strutils.nim");
					nimln(286, "strutils.nim");
					nimln(286, "strutils.nim");
					TMP321 = subInt(last_125422, 1);
					candidate_125415 = copyStrLast(path, first_125424, (NI64)(TMP321));
					nimln(1855, "os.nim");
					x = HEX2F_117299(candidate_125415, result);
					nimln(1856, "os.nim");
					{
						NIM_BOOL LOC23;
						nimln(1856, "os.nim");
						LOC23 = 0;
						LOC23 = nosexistsFile(x);
						if (!LOC23) goto LA24;
						nimln(1856, "os.nim");
						nimln(1856, "os.nim");
						result = copyString(x);
						goto BeforeRet;
					}
					LA24: ;
					nimln(287, "strutils.nim");
					last_125422 = addInt(last_125422, 1);
				} LA16: ;
			}
		}
		LA13: ;
	}
	nimln(1857, "os.nim");
	result = copyString(((NimStringDesc*) &TMP316));
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nosexecShellCmd)(NimStringDesc* command) {
	NI result;
	int LOC1;
	nimfr("execShellCmd", "os.nim")
	result = 0;
	nimln(1062, "os.nim");
	nimln(1062, "os.nim");
	nimln(1062, "os.nim");
	LOC1 = 0;
	LOC1 = system(command->data);
	result = ((NI) ((NI32)((NU32)(LOC1) >> (NU32)(((NI32) 8)))));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, oserrormsg_114620)(NI32 errorcode) {
	NimStringDesc* result;
	nimfr("osErrorMsg", "os.nim")
	result = 0;
	nimln(245, "os.nim");
	result = copyString(((NimStringDesc*) &TMP316));
	nimln(261, "os.nim");
	{
		NCSTRING LOC5;
		nimln(261, "os.nim");
		nimln(261, "os.nim");
		if (!!((errorcode == ((NI32) 0)))) goto LA3;
		nimln(262, "os.nim");
		nimln(262, "os.nim");
		nimln(262, "os.nim");
		LOC5 = 0;
		LOC5 = strerror(errorcode);
		result = cstrToNimstr(LOC5);
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, raiseoserror_114809)(NI32 errorcode) {
	oserror3233* e;
	nimfr("raiseOSError", "os.nim")
	e = 0;
	nimln(272, "os.nim");
	e = (oserror3233*) newObj((&NTI114812), sizeof(oserror3233));
	(*e).Sup.Sup.Sup.m_type = (&NTI3233);
	nimln(273, "os.nim");
	(*e).Errorcode = errorcode;
	nimln(274, "os.nim");
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), oserrormsg_114620(errorcode));
	nimln(275, "os.nim");
	{
		NimStringDesc* LOC5;
		nimln(275, "os.nim");
		if (!(((*e).Sup.Sup.message) && ((*e).Sup.Sup.message)->Sup.len == 0)) goto LA3;
		nimln(276, "os.nim");
		LOC5 = 0;
		LOC5 = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP351));
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	LA3: ;
	nimln(277, "os.nim");
	raiseException((Exception*)e, "OSError");
	popFrame();
}

N_NIMCALL(NI32, oslasterror_114841)(void) {
	NI32 result;
	result = 0;
	result = errno;
	return result;
}

N_NIMCALL(NimStringDesc*, nosgetCurrentDir)(void) {
	NimStringDesc* result;
	nimfr("getCurrentDir", "os.nim")
	result = 0;
	nimln(498, "os.nim");
	nimln(498, "os.nim");
	result = mnewString(512);
	nimln(499, "os.nim");
	{
		NCSTRING LOC3;
		NI LOC6;
		nimln(499, "os.nim");
		nimln(499, "os.nim");
		nimln(499, "os.nim");
		LOC3 = 0;
		LOC3 = getcwd(result->data, 512);
		if (!!((LOC3 == NIM_NIL))) goto LA4;
		nimln(500, "os.nim");
		nimln(500, "os.nim");
		LOC6 = 0;
		LOC6 = strlen(result->data);
		result = setLengthStr(result, LOC6);
	}
	goto LA1;
	LA4: ;
	{
		NI32 LOC8;
		nimln(502, "os.nim");
		nimln(502, "os.nim");
		LOC8 = 0;
		LOC8 = oslasterror_114841();
		raiseoserror_114809(LOC8);
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NU16, nosgetFilePermissions)(NimStringDesc* filename) {
	NU16 result;
	struct stat a;
	nimfr("getFilePermissions", "os.nim")
	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&a), 0, sizeof(a));
	nimln(907, "os.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(907, "os.nim");
		nimln(907, "os.nim");
		LOC3 = 0;
		LOC3 = stat(filename->data, (&a));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(907, "os.nim");
		nimln(907, "os.nim");
		LOC6 = 0;
		LOC6 = oslasterror_114841();
		raiseoserror_114809(LOC6);
	}
	LA4: ;
	nimln(908, "os.nim");
	result = 0;
	nimln(909, "os.nim");
	{
		nimln(909, "os.nim");
		nimln(909, "os.nim");
		nimln(909, "os.nim");
		if (!!(((NI32)(a.st_mode & S_IRUSR) == ((NI32) 0)))) goto LA9;
		nimln(909, "os.nim");
		result |= ((NI16)1)<<((((NU8) 2))%(sizeof(NI16)*8));
	}
	LA9: ;
	nimln(910, "os.nim");
	{
		nimln(910, "os.nim");
		nimln(910, "os.nim");
		nimln(910, "os.nim");
		if (!!(((NI32)(a.st_mode & S_IWUSR) == ((NI32) 0)))) goto LA13;
		nimln(910, "os.nim");
		result |= ((NI16)1)<<((((NU8) 1))%(sizeof(NI16)*8));
	}
	LA13: ;
	nimln(911, "os.nim");
	{
		nimln(911, "os.nim");
		nimln(911, "os.nim");
		nimln(911, "os.nim");
		if (!!(((NI32)(a.st_mode & S_IXUSR) == ((NI32) 0)))) goto LA17;
		nimln(911, "os.nim");
		result |= ((NI16)1)<<((((NU8) 0))%(sizeof(NI16)*8));
	}
	LA17: ;
	nimln(913, "os.nim");
	{
		nimln(913, "os.nim");
		nimln(913, "os.nim");
		nimln(913, "os.nim");
		if (!!(((NI32)(a.st_mode & S_IRGRP) == ((NI32) 0)))) goto LA21;
		nimln(913, "os.nim");
		result |= ((NI16)1)<<((((NU8) 5))%(sizeof(NI16)*8));
	}
	LA21: ;
	nimln(914, "os.nim");
	{
		nimln(914, "os.nim");
		nimln(914, "os.nim");
		nimln(914, "os.nim");
		if (!!(((NI32)(a.st_mode & S_IWGRP) == ((NI32) 0)))) goto LA25;
		nimln(914, "os.nim");
		result |= ((NI16)1)<<((((NU8) 4))%(sizeof(NI16)*8));
	}
	LA25: ;
	nimln(915, "os.nim");
	{
		nimln(915, "os.nim");
		nimln(915, "os.nim");
		nimln(915, "os.nim");
		if (!!(((NI32)(a.st_mode & S_IXGRP) == ((NI32) 0)))) goto LA29;
		nimln(915, "os.nim");
		result |= ((NI16)1)<<((((NU8) 3))%(sizeof(NI16)*8));
	}
	LA29: ;
	nimln(917, "os.nim");
	{
		nimln(917, "os.nim");
		nimln(917, "os.nim");
		nimln(917, "os.nim");
		if (!!(((NI32)(a.st_mode & S_IROTH) == ((NI32) 0)))) goto LA33;
		nimln(917, "os.nim");
		result |= ((NI16)1)<<((((NU8) 8))%(sizeof(NI16)*8));
	}
	LA33: ;
	nimln(918, "os.nim");
	{
		nimln(918, "os.nim");
		nimln(918, "os.nim");
		nimln(918, "os.nim");
		if (!!(((NI32)(a.st_mode & S_IWOTH) == ((NI32) 0)))) goto LA37;
		nimln(918, "os.nim");
		result |= ((NI16)1)<<((((NU8) 7))%(sizeof(NI16)*8));
	}
	LA37: ;
	nimln(919, "os.nim");
	{
		nimln(919, "os.nim");
		nimln(919, "os.nim");
		nimln(919, "os.nim");
		if (!!(((NI32)(a.st_mode & S_IXOTH) == ((NI32) 0)))) goto LA41;
		nimln(919, "os.nim");
		result |= ((NI16)1)<<((((NU8) 6))%(sizeof(NI16)*8));
	}
	LA41: ;
	popFrame();
	return result;
}

N_NIMCALL(time_t, nosgetLastModificationTime)(NimStringDesc* file) {
	time_t result;
	struct stat res;
	nimfr("getLastModificationTime", "os.nim")
	result = 0;
	memset((void*)(&res), 0, sizeof(res));
	nimln(437, "os.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(437, "os.nim");
		nimln(437, "os.nim");
		LOC3 = 0;
		LOC3 = stat(file->data, (&res));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(437, "os.nim");
		nimln(437, "os.nim");
		LOC6 = 0;
		LOC6 = oslasterror_114841();
		raiseoserror_114809(LOC6);
	}
	LA4: ;
	nimln(438, "os.nim");
	nimln(438, "os.nim");
	result = res.st_mtime;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nosremoveFile)(NimStringDesc* file) {
	nimfr("removeFile", "os.nim")
	nimln(1048, "os.nim");
	{
		NIM_BOOL LOC3;
		int LOC4;
		oserror3233* e_119603;
		NCSTRING LOC8;
		nimln(1048, "os.nim");
		LOC3 = 0;
		nimln(1048, "os.nim");
		nimln(1048, "os.nim");
		nimln(1048, "os.nim");
		LOC4 = 0;
		LOC4 = remove(file->data);
		LOC3 = !((LOC4 == ((NI32) 0)));
		if (!(LOC3)) goto LA5;
		nimln(1048, "os.nim");
		nimln(1048, "os.nim");
		LOC3 = !((errno == ENOENT));
		LA5: ;
		if (!LOC3) goto LA6;
		e_119603 = 0;
		nimln(2149, "system.nim");
		e_119603 = (oserror3233*) newObj((&NTI114812), sizeof(oserror3233));
		(*e_119603).Sup.Sup.Sup.m_type = (&NTI3233);
		nimln(2150, "system.nim");
		nimln(1049, "os.nim");
		nimln(1049, "os.nim");
		LOC8 = 0;
		LOC8 = strerror(errno);
		asgnRefNoCycle((void**) (&(*e_119603).Sup.Sup.message), cstrToNimstr(LOC8));
		nimln(1049, "os.nim");
		raiseException((Exception*)e_119603, "OSError");
	}
	LA6: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, rawremovedir_121422)(NimStringDesc* dir) {
	nimfr("rawRemoveDir", "os.nim")
	nimln(1335, "os.nim");
	{
		NIM_BOOL LOC3;
		int LOC4;
		NI32 LOC8;
		nimln(1335, "os.nim");
		LOC3 = 0;
		nimln(1335, "os.nim");
		nimln(1335, "os.nim");
		nimln(1335, "os.nim");
		LOC4 = 0;
		LOC4 = rmdir(dir->data);
		LOC3 = !((LOC4 == ((NI32) 0)));
		if (!(LOC3)) goto LA5;
		nimln(1335, "os.nim");
		nimln(1335, "os.nim");
		LOC3 = !((errno == ENOENT));
		LA5: ;
		if (!LOC3) goto LA6;
		nimln(1335, "os.nim");
		nimln(1335, "os.nim");
		LOC8 = 0;
		LOC8 = oslasterror_114841();
		raiseoserror_114809(LOC8);
	}
	LA6: ;
	popFrame();
}

N_NIMCALL(void, nosremoveDir)(NimStringDesc* dir) {
	nimfr("removeDir", "os.nim")
	{
		NU8 kind_121610;
		NimStringDesc* path_121611;
		DIR* d_121615;
		kind_121610 = 0;
		path_121611 = 0;
		nimln(1281, "os.nim");
		d_121615 = opendir(dir->data);
		nimln(1282, "os.nim");
		{
			int LOC35;
			nimln(1282, "os.nim");
			nimln(1282, "os.nim");
			if (!!((d_121615 == NIM_NIL))) goto LA4;
			{
				nimln(1283, "os.nim");
				while (1) {
					struct dirent* x_121617;
					NimStringDesc* y_121619;
					nimln(1284, "os.nim");
					x_121617 = readdir(d_121615);
					nimln(1285, "os.nim");
					{
						nimln(1285, "os.nim");
						if (!(x_121617 == NIM_NIL)) goto LA10;
						nimln(1285, "os.nim");
						goto LA6;
					}
					LA10: ;
					nimln(1286, "os.nim");
					nimln(1286, "os.nim");
					y_121619 = cstrToNimstr(((NCSTRING) ((*x_121617).d_name)));
					nimln(1287, "os.nim");
					{
						NIM_BOOL LOC14;
						struct stat s_121621;
						NU8 k_121623;
						nimln(1287, "os.nim");
						LOC14 = 0;
						nimln(1287, "os.nim");
						nimln(1287, "os.nim");
						LOC14 = !(eqStrings(y_121619, ((NimStringDesc*) &TMP386)));
						if (!(LOC14)) goto LA15;
						nimln(1287, "os.nim");
						nimln(1287, "os.nim");
						LOC14 = !(eqStrings(y_121619, ((NimStringDesc*) &TMP387)));
						LA15: ;
						if (!LOC14) goto LA16;
						memset((void*)(&s_121621), 0, sizeof(s_121621));
						nimln(1289, "os.nim");
						y_121619 = HEX2F_117299(dir, y_121619);
						nimln(1290, "os.nim");
						{
							int LOC20;
							nimln(1290, "os.nim");
							nimln(1290, "os.nim");
							LOC20 = 0;
							LOC20 = lstat(y_121619->data, (&s_121621));
							if (!(LOC20 < ((NI32) 0))) goto LA21;
							nimln(1290, "os.nim");
							goto LA6;
						}
						LA21: ;
						nimln(1291, "os.nim");
						k_121623 = ((NU8) 0);
						nimln(1292, "os.nim");
						{
							NIM_BOOL LOC25;
							nimln(1292, "os.nim");
							LOC25 = 0;
							LOC25 = S_ISDIR(s_121621.st_mode);
							if (!LOC25) goto LA26;
							nimln(1292, "os.nim");
							k_121623 = ((NU8) 2);
						}
						LA26: ;
						nimln(1293, "os.nim");
						{
							NIM_BOOL LOC30;
							nimln(1293, "os.nim");
							LOC30 = 0;
							LOC30 = S_ISLNK(s_121621.st_mode);
							if (!LOC30) goto LA31;
							nimln(1293, "os.nim");
							nimln(1293, "os.nim");
							k_121623 = addInt(k_121623, 1);
						}
						LA31: ;
						nimln(1291, "os.nim");
						kind_121610 = k_121623;
						nimln(1286, "os.nim");
						path_121611 = y_121619;
						nimln(1345, "os.nim");
						switch (kind_121610) {
						case ((NU8) 0):
						case ((NU8) 1):
						case ((NU8) 3):
						{
							nimln(1346, "os.nim");
							nosremoveFile(path_121611);
						}
						break;
						case ((NU8) 2):
						{
							nimln(1347, "os.nim");
							nosremoveDir(path_121611);
						}
						break;
						}
					}
					LA16: ;
				}
			} LA6: ;
			nimln(1295, "os.nim");
			nimln(1295, "os.nim");
			LOC35 = 0;
			LOC35 = closedir(d_121615);
		}
		LA4: ;
	}
	nimln(1348, "os.nim");
	rawremovedir_121422(dir);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit)(void) {
	nimfr("os", "os.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit)(void) {
}

