/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/parseopt.o /home/chronize/Documents/projects/nimkernel/nimcache/parseopt.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct optparser127007 optparser127007;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  optparser127007  {
  TNimObject Sup;
NimStringDesc* Cmd;
NI Pos;
NIM_BOOL Inshortstate;
NU8 Kind;
NimStringDesc* Key;
NimStringDesc* Val;
};
typedef NU8 TY76068[32];
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, initoptparser_127026)(NimStringDesc* cmdline, optparser127007* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, paramcount_123639)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, quoteifcontainswhite_95234)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, paramstr_123609)(NI i);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, parseword_127204)(NimStringDesc* s, NI i, NimStringDesc** w, TY76068 delim);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(void, handleshortoption_127309)(optparser127007* p);
N_NIMCALL(void, nponext)(optparser127007* p);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NimStringDesc*, npocmdLineRest)(optparser127007* p);
N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75028, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
STRING_LITERAL(TMP261, "", 0);
STRING_LITERAL(TMP266, "", 0);
static NIM_CONST TY76068 TMP267 = {
0x01, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST TY76068 TMP268 = {
0x01, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x24,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
extern TFrame* frameptr_16242;
extern TNimType NTI3211; /* RootObj */
TNimType NTI127007; /* OptParser */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
extern TNimType NTI138; /* bool */
TNimType NTI127005; /* CmdLineKind */

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(void, initoptparser_127026)(NimStringDesc* cmdline, optparser127007* Result) {
	nimfr("initOptParser", "parseopt.nim")
	nimln(49, "parseopt.nim");
	(*Result).Pos = 0;
	nimln(50, "parseopt.nim");
	(*Result).Inshortstate = NIM_FALSE;
	nimln(51, "parseopt.nim");
	{
		nimln(51, "parseopt.nim");
		nimln(51, "parseopt.nim");
		if (!!(((cmdline) && (cmdline)->Sup.len == 0))) goto LA3;
		nimln(52, "parseopt.nim");
		unsureAsgnRef((void**) (&(*Result).Cmd), copyString(cmdline));
	}
	goto LA1;
	LA3: ;
	{
		nimln(54, "parseopt.nim");
		unsureAsgnRef((void**) (&(*Result).Cmd), copyString(((NimStringDesc*) &TMP261)));
		{
			NI i_127042;
			NI HEX3Atmp_127045;
			NI res_127048;
			i_127042 = 0;
			HEX3Atmp_127045 = 0;
			nimln(55, "parseopt.nim");
			HEX3Atmp_127045 = paramcount_123639();
			nimln(1569, "system.nim");
			res_127048 = 1;
			{
				nimln(1570, "system.nim");
				while (1) {
					NimStringDesc* LOC9;
					NimStringDesc* LOC10;
					NimStringDesc* LOC11;
					nimln(1570, "system.nim");
					if (!(res_127048 <= HEX3Atmp_127045)) goto LA8;
					nimln(1569, "system.nim");
					i_127042 = res_127048;
					nimln(56, "parseopt.nim");
					nimln(56, "parseopt.nim");
					LOC9 = 0;
					nimln(56, "parseopt.nim");
					nimln(56, "parseopt.nim");
					LOC10 = 0;
					LOC10 = paramstr_123609(i_127042);
					LOC11 = 0;
					LOC11 = quoteifcontainswhite_95234(LOC10);
					LOC9 = rawNewString((*Result).Cmd->Sup.len + LOC11->Sup.len + 1);
appendString(LOC9, (*Result).Cmd);
appendString(LOC9, LOC11);
appendChar(LOC9, 32);
					unsureAsgnRef((void**) (&(*Result).Cmd), LOC9);
					nimln(1572, "system.nim");
					res_127048 = addInt(res_127048, 1);
				} LA8: ;
			}
		}
	}
	LA1: ;
	nimln(57, "parseopt.nim");
	(*Result).Kind = ((NU8) 0);
	nimln(58, "parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).Key), copyString(((NimStringDesc*) &TMP266)));
	nimln(59, "parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).Val), copyString(((NimStringDesc*) &TMP266)));
	popFrame();
}

N_NIMCALL(NI, parseword_127204)(NimStringDesc* s, NI i, NimStringDesc** w, TY76068 delim) {
	NI result;
	nimfr("parseWord", "parseopt.nim")
	result = 0;
	nimln(63, "parseopt.nim");
	result = i;
	nimln(64, "parseopt.nim");
	{
		nimln(64, "parseopt.nim");
		if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[result]) == (NU8)(34))) goto LA3;
		nimln(65, "parseopt.nim");
		result = addInt(result, 1);
		{
			nimln(66, "parseopt.nim");
			while (1) {
				nimln(66, "parseopt.nim");
				nimln(66, "parseopt.nim");
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				if (!!((((NU8)(s->data[result])) == ((NU8)(0)) || ((NU8)(s->data[result])) == ((NU8)(34))))) goto LA6;
				nimln(67, "parseopt.nim");
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				(*w) = addChar((*w), s->data[result]);
				nimln(68, "parseopt.nim");
				result = addInt(result, 1);
			} LA6: ;
		}
		nimln(69, "parseopt.nim");
		{
			nimln(69, "parseopt.nim");
			if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
			if (!((NU8)(s->data[result]) == (NU8)(34))) goto LA9;
			nimln(69, "parseopt.nim");
			result = addInt(result, 1);
		}
		LA9: ;
	}
	goto LA1;
	LA3: ;
	{
		{
			nimln(71, "parseopt.nim");
			while (1) {
				nimln(71, "parseopt.nim");
				nimln(71, "parseopt.nim");
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				if (!!(((delim[((NU8)(s->data[result]))/8] &(1<<(((NU8)(s->data[result]))%8)))!=0))) goto LA13;
				nimln(72, "parseopt.nim");
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				(*w) = addChar((*w), s->data[result]);
				nimln(73, "parseopt.nim");
				result = addInt(result, 1);
			} LA13: ;
		}
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, handleshortoption_127309)(optparser127007* p) {
	NI i;
	nimfr("handleShortOption", "parseopt.nim")
	nimln(76, "parseopt.nim");
	i = (*p).Pos;
	nimln(77, "parseopt.nim");
	(*p).Kind = ((NU8) 3);
	nimln(78, "parseopt.nim");
	if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
	(*p).Key = addChar((*p).Key, (*p).Cmd->data[i]);
	nimln(79, "parseopt.nim");
	i = addInt(i, 1);
	nimln(80, "parseopt.nim");
	(*p).Inshortstate = NIM_TRUE;
	{
		nimln(81, "parseopt.nim");
		while (1) {
			nimln(81, "parseopt.nim");
			if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
			if (!(((NU8)((*p).Cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).Cmd->data[i])) == ((NU8)(32)))) goto LA2;
			nimln(82, "parseopt.nim");
			i = addInt(i, 1);
			nimln(83, "parseopt.nim");
			(*p).Inshortstate = NIM_FALSE;
		} LA2: ;
	}
	nimln(84, "parseopt.nim");
	{
		nimln(84, "parseopt.nim");
		if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
		if (!(((NU8)((*p).Cmd->data[i])) == ((NU8)(58)) || ((NU8)((*p).Cmd->data[i])) == ((NU8)(61)))) goto LA5;
		nimln(85, "parseopt.nim");
		i = addInt(i, 1);
		nimln(86, "parseopt.nim");
		(*p).Inshortstate = NIM_FALSE;
		{
			nimln(87, "parseopt.nim");
			while (1) {
				nimln(87, "parseopt.nim");
				if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
				if (!(((NU8)((*p).Cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).Cmd->data[i])) == ((NU8)(32)))) goto LA8;
				nimln(87, "parseopt.nim");
				i = addInt(i, 1);
			} LA8: ;
		}
		nimln(88, "parseopt.nim");
		i = parseword_127204((*p).Cmd, i, (&(*p).Val), TMP267);
	}
	LA5: ;
	nimln(89, "parseopt.nim");
	{
		nimln(89, "parseopt.nim");
		if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
		if (!((NU8)((*p).Cmd->data[i]) == (NU8)(0))) goto LA11;
		nimln(89, "parseopt.nim");
		(*p).Inshortstate = NIM_FALSE;
	}
	LA11: ;
	nimln(90, "parseopt.nim");
	(*p).Pos = i;
	popFrame();
}

N_NIMCALL(void, nponext)(optparser127007* p) {
	NI i;
	nimfr("next", "parseopt.nim")
	nimln(95, "parseopt.nim");
	i = (*p).Pos;
	{
		nimln(96, "parseopt.nim");
		while (1) {
			nimln(96, "parseopt.nim");
			if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
			if (!(((NU8)((*p).Cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).Cmd->data[i])) == ((NU8)(32)))) goto LA2;
			nimln(96, "parseopt.nim");
			i = addInt(i, 1);
		} LA2: ;
	}
	nimln(97, "parseopt.nim");
	(*p).Pos = i;
	nimln(98, "parseopt.nim");
	(*p).Key = setLengthStr((*p).Key, 0);
	nimln(99, "parseopt.nim");
	(*p).Val = setLengthStr((*p).Val, 0);
	nimln(100, "parseopt.nim");
	{
		if (!(*p).Inshortstate) goto LA5;
		nimln(101, "parseopt.nim");
		handleshortoption_127309(p);
		nimln(102, "parseopt.nim");
		goto BeforeRet;
	}
	LA5: ;
	nimln(103, "parseopt.nim");
	if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
	switch (((NU8)((*p).Cmd->data[i]))) {
	case 0:
	{
		nimln(105, "parseopt.nim");
		(*p).Kind = ((NU8) 0);
	}
	break;
	case 45:
	{
		nimln(107, "parseopt.nim");
		i = addInt(i, 1);
		nimln(108, "parseopt.nim");
		{
			nimln(108, "parseopt.nim");
			if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
			if (!((NU8)((*p).Cmd->data[i]) == (NU8)(45))) goto LA11;
			nimln(109, "parseopt.nim");
			(*p).Kind = ((NU8) 2);
			nimln(110, "parseopt.nim");
			i = addInt(i, 1);
			nimln(111, "parseopt.nim");
			i = parseword_127204((*p).Cmd, i, (&(*p).Key), TMP268);
			{
				nimln(112, "parseopt.nim");
				while (1) {
					nimln(112, "parseopt.nim");
					if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
					if (!(((NU8)((*p).Cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).Cmd->data[i])) == ((NU8)(32)))) goto LA14;
					nimln(112, "parseopt.nim");
					i = addInt(i, 1);
				} LA14: ;
			}
			nimln(113, "parseopt.nim");
			{
				nimln(113, "parseopt.nim");
				if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
				if (!(((NU8)((*p).Cmd->data[i])) == ((NU8)(58)) || ((NU8)((*p).Cmd->data[i])) == ((NU8)(61)))) goto LA17;
				nimln(114, "parseopt.nim");
				i = addInt(i, 1);
				{
					nimln(115, "parseopt.nim");
					while (1) {
						nimln(115, "parseopt.nim");
						if ((NU)(i) > (NU)((*p).Cmd->Sup.len)) raiseIndexError();
						if (!(((NU8)((*p).Cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).Cmd->data[i])) == ((NU8)(32)))) goto LA20;
						nimln(115, "parseopt.nim");
						i = addInt(i, 1);
					} LA20: ;
				}
				nimln(116, "parseopt.nim");
				(*p).Pos = parseword_127204((*p).Cmd, i, (&(*p).Val), TMP267);
			}
			goto LA15;
			LA17: ;
			{
				nimln(118, "parseopt.nim");
				(*p).Pos = i;
			}
			LA15: ;
		}
		goto LA9;
		LA11: ;
		{
			nimln(120, "parseopt.nim");
			(*p).Pos = i;
			nimln(121, "parseopt.nim");
			handleshortoption_127309(p);
		}
		LA9: ;
	}
	break;
	default:
	{
		nimln(123, "parseopt.nim");
		(*p).Kind = ((NU8) 1);
		nimln(124, "parseopt.nim");
		(*p).Pos = parseword_127204((*p).Cmd, i, (&(*p).Key), TMP267);
	}
	break;
	}
	BeforeRet: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, npocmdLineRest)(optparser127007* p) {
	NimStringDesc* result;
	NI TMP270;
	NimStringDesc* LOC1;
	nimfr("cmdLineRest", "parseopt.nim")
	result = 0;
	nimln(128, "parseopt.nim");
	nimln(128, "parseopt.nim");
	nimln(128, "parseopt.nim");
	nimln(128, "parseopt.nim");
	nimln(128, "parseopt.nim");
	TMP270 = subInt((*p).Cmd->Sup.len, 1);
	LOC1 = 0;
	LOC1 = copyStrLast((*p).Cmd, (*p).Pos, (NI64)(TMP270));
	result = nsuStrip(LOC1, NIM_TRUE, NIM_TRUE);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_parseoptInit)(void) {
	nimfr("parseopt", "parseopt.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_parseoptDatInit)(void) {
static TNimNode* TMP366[6];
static TNimNode* TMP367[4];
NI TMP369;
static char* NIM_CONST TMP368[4] = {
"cmdEnd", 
"cmdArgument", 
"cmdLongOption", 
"cmdShortOption"};
static TNimNode TMP137[12];
NTI127007.size = sizeof(optparser127007);
NTI127007.kind = 17;
NTI127007.base = (&NTI3211);
TMP366[0] = &TMP137[1];
TMP137[1].kind = 1;
TMP137[1].offset = offsetof(optparser127007, Cmd);
TMP137[1].typ = (&NTI149);
TMP137[1].name = "cmd";
TMP366[1] = &TMP137[2];
TMP137[2].kind = 1;
TMP137[2].offset = offsetof(optparser127007, Pos);
TMP137[2].typ = (&NTI108);
TMP137[2].name = "pos";
TMP366[2] = &TMP137[3];
TMP137[3].kind = 1;
TMP137[3].offset = offsetof(optparser127007, Inshortstate);
TMP137[3].typ = (&NTI138);
TMP137[3].name = "inShortState";
TMP366[3] = &TMP137[4];
NTI127005.size = sizeof(NU8);
NTI127005.kind = 14;
NTI127005.base = 0;
NTI127005.flags = 3;
for (TMP369 = 0; TMP369 < 4; TMP369++) {
TMP137[TMP369+5].kind = 1;
TMP137[TMP369+5].offset = TMP369;
TMP137[TMP369+5].name = TMP368[TMP369];
TMP367[TMP369] = &TMP137[TMP369+5];
}
TMP137[9].len = 4; TMP137[9].kind = 2; TMP137[9].sons = &TMP367[0];
NTI127005.node = &TMP137[9];
TMP137[4].kind = 1;
TMP137[4].offset = offsetof(optparser127007, Kind);
TMP137[4].typ = (&NTI127005);
TMP137[4].name = "kind";
TMP366[4] = &TMP137[10];
TMP137[10].kind = 1;
TMP137[10].offset = offsetof(optparser127007, Key);
TMP137[10].typ = (&NTI149);
TMP137[10].name = "key";
TMP366[5] = &TMP137[11];
TMP137[11].kind = 1;
TMP137[11].offset = offsetof(optparser127007, Val);
TMP137[11].typ = (&NTI149);
TMP137[11].name = "val";
TMP137[0].len = 6; TMP137[0].kind = 2; TMP137[0].sons = &TMP366[0];
NTI127007.node = &TMP137[0];
}

