/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/rdstdin.o /home/chronize/Documents/projects/nimkernel/nimcache/rdstdin.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NCSTRING, TY139887) (NCSTRING a2);
typedef N_CDECL_PTR(void, TY141071) (NCSTRING a2);
typedef N_CDECL_PTR(int, tcommandfunc137222) (int a2, int a3);
typedef N_CDECL_PTR(int, TY139929) (int a2, tcommandfunc137222 a3);
N_NIMCALL(NimStringDesc*, readlinefromstdin_142001)(NimStringDesc* prompt);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, readlinefromstdin_142013)(NimStringDesc* prompt, NimStringDesc** line);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_CDECL(int, donothing_142027)(int a, int b);
extern TY139887 Dl_139886;
extern TY141071 Dl_141070;
extern TFrame* frameptr_16242;
extern TY139929 Dl_139928;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(NimStringDesc*, readlinefromstdin_142001)(NimStringDesc* prompt) {
	NimStringDesc* result;
	NCSTRING buffer;
	nimfr("readLineFromStdin", "rdstdin.nim")
	result = 0;
	nimln(39, "rdstdin.nim");
	buffer = Dl_139886(prompt->data);
	nimln(40, "rdstdin.nim");
	{
		nimln(40, "rdstdin.nim");
		if (!buffer == 0) goto LA3;
		nimln(40, "rdstdin.nim");
		exit(0);
	}
	LA3: ;
	nimln(41, "rdstdin.nim");
	nimln(41, "rdstdin.nim");
	result = cstrToNimstr(buffer);
	nimln(42, "rdstdin.nim");
	{
		nimln(42, "rdstdin.nim");
		nimln(42, "rdstdin.nim");
		if (!(0 < result->Sup.len)) goto LA7;
		nimln(43, "rdstdin.nim");
		Dl_141070(buffer);
	}
	LA7: ;
	nimln(44, "rdstdin.nim");
	free(buffer);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, readlinefromstdin_142013)(NimStringDesc* prompt, NimStringDesc** line) {
	NIM_BOOL result;
	NCSTRING buffer;
	nimfr("readLineFromStdin", "rdstdin.nim")
	result = 0;
	nimln(48, "rdstdin.nim");
	buffer = Dl_139886(prompt->data);
	nimln(49, "rdstdin.nim");
	{
		nimln(49, "rdstdin.nim");
		if (!buffer == 0) goto LA3;
		nimln(49, "rdstdin.nim");
		exit(0);
	}
	LA3: ;
	nimln(50, "rdstdin.nim");
	nimln(50, "rdstdin.nim");
	unsureAsgnRef((void**) (&(*line)), cstrToNimstr(buffer));
	nimln(51, "rdstdin.nim");
	{
		nimln(51, "rdstdin.nim");
		nimln(51, "rdstdin.nim");
		if (!(0 < (*line)->Sup.len)) goto LA7;
		nimln(52, "rdstdin.nim");
		Dl_141070(buffer);
	}
	LA7: ;
	nimln(53, "rdstdin.nim");
	free(buffer);
	nimln(55, "rdstdin.nim");
	result = NIM_TRUE;
	popFrame();
	return result;
}

N_CDECL(int, donothing_142027)(int a, int b) {
	int result;
	nimfr("doNothing", "rdstdin.nim")
	result = 0;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_rdstdinInit)(void) {
	int LOC1;
	nimfr("rdstdin", "rdstdin.nim")
	nimln(61, "rdstdin.nim");
	nimln(61, "rdstdin.nim");
	LOC1 = 0;
	LOC1 = Dl_139928(((int) 9), donothing_142027);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_rdstdinDatInit)(void) {
}

