/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/readline.o /home/chronize/Documents/projects/nimkernel/nimcache/readline.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tundolist138446 tundolist138446;
typedef struct tfunmap138606 tfunmap138606;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NCSTRING, thookfunc138245) (NCSTRING a2);
typedef N_CDECL_PTR(NCSTRING, TY139887) (NCSTRING a2);
typedef N_CDECL_PTR(int, tcommandfunc137222) (int a2, int a3);
typedef N_CDECL_PTR(int, TY139929) (int a2, tcommandfunc137222 a3);
struct  tundolist138446  {
tundolist138446* Next;
int Start;
int Theend;
NCSTRING Text;
NU8 What;
};
struct  tfunmap138606  {
NCSTRING Name;
tcommandfunc137222 Function;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP295, "libreadline.so.6", 16);
STRING_LITERAL(TMP296, "libreadline.so.6.0", 18);
STRING_LITERAL(TMP297, "libreadline.so.6(|.0)", 21);
static void* TMP294;
thookfunc138245* Dl_138251;
thookfunc138245* Dl_138252;
NCSTRING** Dl_138253;
NCSTRING** Dl_138254;
tundolist138446** Dl_138457;
tfunmap138606*** Dl_138614;
TY139887 Dl_139886;
TY139929 Dl_139928;
extern TFrame* frameptr_16242;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_readlineInit)(void) {
	nimfr("readline", "readline.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_readlineDatInit)(void) {
if (!((TMP294 = nimLoadLibrary((NimStringDesc*) &TMP295))
||(TMP294 = nimLoadLibrary((NimStringDesc*) &TMP296))
)) nimLoadLibraryError((NimStringDesc*) &TMP297);
Dl_138251 = (thookfunc138245*) nimGetProcAddr(TMP294, "tilde_expansion_preexpansion_hook");
Dl_138252 = (thookfunc138245*) nimGetProcAddr(TMP294, "tilde_expansion_failure_hook");
Dl_138253 = (NCSTRING**) nimGetProcAddr(TMP294, "tilde_additional_prefixes");
Dl_138254 = (NCSTRING**) nimGetProcAddr(TMP294, "tilde_additional_suffixes");
Dl_138457 = (tundolist138446**) nimGetProcAddr(TMP294, "rl_undo_list");
Dl_138614 = (tfunmap138606***) nimGetProcAddr(TMP294, "funmap");
	Dl_139886 = (TY139887) nimGetProcAddr(TMP294, "readline");
	Dl_139928 = (TY139929) nimGetProcAddr(TMP294, "rl_bind_key");
}

