/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc -c  -w -I$lib -ffreestanding -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/system.o /home/chronize/Documents/projects/nimkernel/nimcache/system.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct Exception Exception;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tpos9009 tpos9009;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef N_NIMCALL_PTR(NIM_BOOL, TY8018) (Exception* e);
typedef N_NIMCALL_PTR(NIM_BOOL, TY8023) (Exception* e);
typedef N_NIMCALL_PTR(void, TY8028) (void);
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tpos9009 {
NI Field0;
NI Field1;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, panic_10013)(NimStringDesc* s);
N_NIMCALL(void, rawoutput_10001)(NimStringDesc* s);
N_NIMCALL(void, writestring_9271)(NU16* vram, NimStringDesc* text, NU8 color, tpos9009 pos);
N_NIMCALL(NU8, makecolor_9057)(NU8 bg, NU8 fg);
STRING_LITERAL(TMP8, "Error: ", 7);
NIM_CONST tpos9009 TMP9 = {0,
24}
;
NIM_CONST tpos9009 TMP10 = {7,
24}
;
STRING_LITERAL(TMP11, "index out of bounds", 19);
NI nim_program_result;
TY8018 globalraisehook_8022;
TY8023 localraisehook_8027;
TY8028 outofmemhook_8030;

N_NIMCALL(void, rawoutput_10001)(NimStringDesc* s) {
	NU16* vram;
	NU8 LOC1;
	NU8 LOC2;
	vram = ((NU16*) 753664);
	LOC1 = 0;
	LOC1 = makecolor_9057(((NU8) 15), ((NU8) 4));
	writestring_9271(vram, ((NimStringDesc*) &TMP8), LOC1, TMP9);
	LOC2 = 0;
	LOC2 = makecolor_9057(((NU8) 15), ((NU8) 4));
	writestring_9271(vram, s, LOC2, TMP10);
}

N_NIMCALL(void, panic_10013)(NimStringDesc* s) {
	rawoutput_10001(s);
}

N_NOINLINE(void, raiseIndexError)(void) {
	panic_10013(((NimStringDesc*) &TMP11));
}
NIM_EXTERNC N_NOINLINE(void, systemInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void) {
}

