/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/tables.o /home/chronize/Documents/projects/nimkernel/nimcache/tables.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct orderedtable143031 orderedtable143031;
typedef struct orderedkeyvaluepairseq143034 orderedkeyvaluepairseq143034;
typedef struct orderedkeyvaluepair143037 orderedkeyvaluepair143037;
typedef struct ptaskHEX3Aobjecttype143013 ptaskHEX3Aobjecttype143013;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell45135 tcell45135;
typedef struct tcellset45147 tcellset45147;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct orderedkeyvaluepair143037 {
NU8 Field0;
NI Field1;
NimStringDesc* Field2;
ptaskHEX3Aobjecttype143013* Field3;
};
struct  orderedtable143031  {
orderedkeyvaluepairseq143034* Data;
NI Counter;
NI First;
NI Last;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} ttaskfunction143010;
struct  ptaskHEX3Aobjecttype143013  {
NimStringDesc* Desc;
ttaskfunction143010 Action;
};
typedef NI TY26620[8];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct orderedkeyvaluepairseq143034 {
  TGenericSeq Sup;
  orderedkeyvaluepair143037 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_134302)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_85225)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_134410)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NIM_BOOL, ispoweroftwo_131518)(NI x);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP313)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, rawget_143302)(orderedtable143031* t_143309, NimStringDesc* key_143312);
N_NIMCALL(NI, hash_128842)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51225)(tcell45135* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c);
static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c);
N_NOINLINE(void, incl_45871)(tcellset45147* s, tcell45135* cell);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, decref_50804)(tcell45135* c);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, enlarge_145069)(orderedtable143031* t_145078);
N_NIMCALL(void, rawinsert_145128)(orderedtable143031* t_145137, orderedkeyvaluepairseq143034** data_145145, NimStringDesc* key_145149, ptaskHEX3Aobjecttype143013* val_145151);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
STRING_LITERAL(TMP282, "length > counter ", 17);
STRING_LITERAL(TMP304, "isPowerOfTwo(initialSize) ", 26);
extern TFrame* frameptr_16242;
TNimType NTI143037; /* OrderedKeyValuePair */
TNimType NTI134009; /* SlotEnum */
extern TNimType NTI108; /* int */
extern TNimType NTI149; /* string */
extern TNimType NTI143008; /* PTask */
TNimType NTI143034; /* OrderedKeyValuePairSeq */
TNimType NTI143031; /* OrderedTable */
extern tgcheap47216 gch_47244;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_134302)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP283;
	NI TMP284;
	NI TMP285;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(120, "tables.nim");
	{
		nimln(120, "tables.nim");
		nimln(120, "tables.nim");
		if (!!((counter < length))) goto LA3;
		nimln(120, "tables.nim");
		failedassertimpl_85225(((NimStringDesc*) &TMP282));
	}
	LA3: ;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	LOC5 = 0;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP283 = mulInt(length, 2);
	nimln(121, "tables.nim");
	TMP284 = mulInt(counter, 3);
	LOC5 = ((NI64)(TMP283) < (NI64)(TMP284));
	if (LOC5) goto LA6;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP285 = subInt(length, counter);
	LOC5 = ((NI64)(TMP285) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_134410)(NI h, NI maxhash) {
	NI result;
	NI TMP286;
	NI TMP287;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	TMP286 = mulInt(5, h);
	TMP287 = addInt((NI64)(TMP286), 1);
	result = (NI)((NI64)(TMP287) & maxhash);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP313)(void* p, NI op) {
	orderedkeyvaluepairseq143034* a;
	NI LOC1;
	a = (orderedkeyvaluepairseq143034*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	nimGCvisit((void*)a->data[LOC1].Field3, op);
	}
}

N_NIMCALL(void, initorderedtable_143023)(NI initialsize_143028, orderedtable143031* Result) {
	nimfr("initOrderedTable", "tables.nim")
	nimln(469, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(469, "tables.nim");
		nimln(469, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_131518(initialsize_143028);
		if (!!(LOC3)) goto LA4;
		nimln(469, "tables.nim");
		failedassertimpl_85225(((NimStringDesc*) &TMP304));
	}
	LA4: ;
	nimln(470, "tables.nim");
	(*Result).Counter = 0;
	nimln(471, "tables.nim");
	(*Result).First = -1;
	nimln(472, "tables.nim");
	(*Result).Last = -1;
	nimln(473, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (orderedkeyvaluepairseq143034*) newSeq((&NTI143034), initialsize_143028));
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, rawget_143302)(orderedtable143031* t_143309, NimStringDesc* key_143312) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_128842(key_143312);
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & ((*t_143309).Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)((*t_143309).Data->Sup.len)) raiseIndexError();
			if (!!(((*t_143309).Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)((*t_143309).Data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings((*t_143309).Data->data[h].Field2, key_143312);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)((*t_143309).Data->Sup.len)) raiseIndexError();
				LOC6 = ((*t_143309).Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_134410(h, ((*t_143309).Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(ptaskHEX3Aobjecttype143013*, HEX5BHEX5D_143288)(orderedtable143031* t_143295, NimStringDesc* key_143298) {
	ptaskHEX3Aobjecttype143013* result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(419, "tables.nim");
	index = rawget_143302(t_143295, key_143298);
	nimln(420, "tables.nim");
	{
		nimln(420, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(420, "tables.nim");
		if ((NU)(index) >= (NU)((*t_143295).Data->Sup.len)) raiseIndexError();
		result = (*t_143295).Data->data[index].Field3;
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, haskey_143914)(orderedtable143031* t_143921, NimStringDesc* key_143924) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	nimln(431, "tables.nim");
	nimln(431, "tables.nim");
	nimln(431, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_143302(t_143921, key_143924);
	result = (0 <= LOC1);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_48867)(tcell45135* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49629)(tcell45135* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45871((&gch_47244.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51225)(tcell45135* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48867(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, decref_50804)(tcell45135* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50404(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48867(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49629(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45135* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48846(src);
		incref_51225(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45135* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48846((*dest));
		decref_50804(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45135* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48846(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50404(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_145128)(orderedtable143031* t_145137, orderedkeyvaluepairseq143034** data_145145, NimStringDesc* key_145149, ptaskHEX3Aobjecttype143013* val_145151) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_128842(key_145149);
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_145145)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_145145)->Sup.len)) raiseIndexError();
			if (!((*data_145145)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_134410(h, ((*data_145145)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_145145)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data_145145)->data[h].Field2; (*data_145145)->data[h].Field2 = copyStringRC1(key_145149);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_145145)->Sup.len)) raiseIndexError();
	asgnRef((void**) (&(*data_145145)->data[h].Field3), val_145151);
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_145145)->Sup.len)) raiseIndexError();
	(*data_145145)->data[h].Field0 = ((NU8) 1);
	nimln(437, "tables.nim");
	if ((NU)(h) >= (NU)((*data_145145)->Sup.len)) raiseIndexError();
	(*data_145145)->data[h].Field1 = -1;
	nimln(438, "tables.nim");
	{
		nimln(438, "tables.nim");
		if (!((*t_145137).First < 0)) goto LA7;
		nimln(438, "tables.nim");
		(*t_145137).First = h;
	}
	LA7: ;
	nimln(439, "tables.nim");
	{
		nimln(439, "tables.nim");
		if (!(0 <= (*t_145137).Last)) goto LA11;
		nimln(439, "tables.nim");
		if ((NU)((*t_145137).Last) >= (NU)((*data_145145)->Sup.len)) raiseIndexError();
		(*data_145145)->data[(*t_145137).Last].Field1 = h;
	}
	LA11: ;
	nimln(440, "tables.nim");
	(*t_145137).Last = h;
	popFrame();
}

N_NIMCALL(void, enlarge_145069)(orderedtable143031* t_145078) {
	orderedkeyvaluepairseq143034* n;
	NI TMP381;
	NI h_145112;
	orderedkeyvaluepairseq143034* LOC7;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(444, "tables.nim");
	nimln(444, "tables.nim");
	nimln(444, "tables.nim");
	TMP381 = mulInt((*t_145078).Data->Sup.len, 2);
	n = (orderedkeyvaluepairseq143034*) newSeq((&NTI143034), (NI64)(TMP381));
	nimln(445, "tables.nim");
	h_145112 = (*t_145078).First;
	nimln(446, "tables.nim");
	(*t_145078).First = -1;
	nimln(447, "tables.nim");
	(*t_145078).Last = -1;
	{
		nimln(448, "tables.nim");
		while (1) {
			NI nxt;
			nimln(448, "tables.nim");
			if (!(0 <= h_145112)) goto LA2;
			nimln(449, "tables.nim");
			if ((NU)(h_145112) >= (NU)((*t_145078).Data->Sup.len)) raiseIndexError();
			nxt = (*t_145078).Data->data[h_145112].Field1;
			nimln(450, "tables.nim");
			{
				nimln(450, "tables.nim");
				if ((NU)(h_145112) >= (NU)((*t_145078).Data->Sup.len)) raiseIndexError();
				if (!((*t_145078).Data->data[h_145112].Field0 == ((NU8) 1))) goto LA5;
				nimln(451, "tables.nim");
				if ((NU)(h_145112) >= (NU)((*t_145078).Data->Sup.len)) raiseIndexError();
				if ((NU)(h_145112) >= (NU)((*t_145078).Data->Sup.len)) raiseIndexError();
				rawinsert_145128(t_145078, (&n), (*t_145078).Data->data[h_145112].Field2, (*t_145078).Data->data[h_145112].Field3);
			}
			LA5: ;
			nimln(452, "tables.nim");
			h_145112 = nxt;
		} LA2: ;
	}
	nimln(453, "tables.nim");
	LOC7 = 0;
	LOC7 = (*t_145078).Data;
	unsureAsgnRef((void**) (&(*t_145078).Data), n);
	n = LOC7;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_145024)(orderedtable143031* t_145033, NimStringDesc* key_145037, ptaskHEX3Aobjecttype143013* val_145039) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_143302((&(*t_145033)), key_145037);
	nimln(190, "tables.nim");
	{
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_145033).Data->Sup.len)) raiseIndexError();
		asgnRef((void**) (&(*t_145033).Data->data[index].Field3), val_145039);
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC8;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_134302((*t_145033).Data->Sup.len, (*t_145033).Counter);
			if (!LOC8) goto LA9;
			nimln(184, "tables.nim");
			enlarge_145069(t_145033);
		}
		LA9: ;
		nimln(185, "tables.nim");
		rawinsert_145128(t_145033, (&(*t_145033).Data), key_145037, val_145039);
		nimln(186, "tables.nim");
		(*t_145033).Counter = addInt((*t_145033).Counter, 1);
	}
	LA1: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_tablesDatInit)(void) {
static TNimNode* TMP305[4];
static TNimNode* TMP306[3];
NI TMP308;
static char* NIM_CONST TMP307[3] = {
"seEmpty", 
"seFilled", 
"seDeleted"};
static TNimNode* TMP314[4];
static TNimNode TMP271[14];
NTI143037.size = sizeof(orderedkeyvaluepair143037);
NTI143037.kind = 18;
NTI143037.base = 0;
TMP305[0] = &TMP271[1];
NTI134009.size = sizeof(NU8);
NTI134009.kind = 14;
NTI134009.base = 0;
NTI134009.flags = 3;
for (TMP308 = 0; TMP308 < 3; TMP308++) {
TMP271[TMP308+2].kind = 1;
TMP271[TMP308+2].offset = TMP308;
TMP271[TMP308+2].name = TMP307[TMP308];
TMP306[TMP308] = &TMP271[TMP308+2];
}
TMP271[5].len = 3; TMP271[5].kind = 2; TMP271[5].sons = &TMP306[0];
NTI134009.node = &TMP271[5];
TMP271[1].kind = 1;
TMP271[1].offset = offsetof(orderedkeyvaluepair143037, Field0);
TMP271[1].typ = (&NTI134009);
TMP271[1].name = "Field0";
TMP305[1] = &TMP271[6];
TMP271[6].kind = 1;
TMP271[6].offset = offsetof(orderedkeyvaluepair143037, Field1);
TMP271[6].typ = (&NTI108);
TMP271[6].name = "Field1";
TMP305[2] = &TMP271[7];
TMP271[7].kind = 1;
TMP271[7].offset = offsetof(orderedkeyvaluepair143037, Field2);
TMP271[7].typ = (&NTI149);
TMP271[7].name = "Field2";
TMP305[3] = &TMP271[8];
TMP271[8].kind = 1;
TMP271[8].offset = offsetof(orderedkeyvaluepair143037, Field3);
TMP271[8].typ = (&NTI143008);
TMP271[8].name = "Field3";
TMP271[0].len = 4; TMP271[0].kind = 2; TMP271[0].sons = &TMP305[0];
NTI143037.node = &TMP271[0];
NTI143034.size = sizeof(orderedkeyvaluepairseq143034*);
NTI143034.kind = 24;
NTI143034.base = (&NTI143037);
NTI143034.marker = TMP313;
NTI143031.size = sizeof(orderedtable143031);
NTI143031.kind = 18;
NTI143031.base = 0;
TMP314[0] = &TMP271[10];
TMP271[10].kind = 1;
TMP271[10].offset = offsetof(orderedtable143031, Data);
TMP271[10].typ = (&NTI143034);
TMP271[10].name = "data";
TMP314[1] = &TMP271[11];
TMP271[11].kind = 1;
TMP271[11].offset = offsetof(orderedtable143031, Counter);
TMP271[11].typ = (&NTI108);
TMP271[11].name = "counter";
TMP314[2] = &TMP271[12];
TMP271[12].kind = 1;
TMP271[12].offset = offsetof(orderedtable143031, First);
TMP271[12].typ = (&NTI108);
TMP271[12].name = "first";
TMP314[3] = &TMP271[13];
TMP271[13].kind = 1;
TMP271[13].offset = offsetof(orderedtable143031, Last);
TMP271[13].typ = (&NTI108);
TMP271[13].name = "last";
TMP271[9].len = 4; TMP271[9].kind = 2; TMP271[9].sons = &TMP314[0];
NTI143031.node = &TMP271[9];
}

