/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/times.o /home/chronize/Documents/projects/nimkernel/nimcache/times.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <sys/time.h>

#include <string.h>

#include <time.h>

#include <sys/select.h>
typedef struct timeinterval101207 timeinterval101207;
typedef struct timeinfo101205 timeinfo101205;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY101352 TY101352;
typedef struct slice84465 slice84465;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct tcell45135 tcell45135;
typedef struct tcellseq45151 tcellseq45151;
typedef struct tgcheap47216 tgcheap47216;
typedef struct tcellset45147 tcellset45147;
typedef struct tpagedesc45143 tpagedesc45143;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47214 tgcstat47214;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
struct  timeinterval101207  {
NI Miliseconds;
NI Seconds;
NI Minutes;
NI Hours;
NI Days;
NI Months;
NI Years;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  timeinfo101205  {
  TNimObject Sup;
NI Second;
NI Minute;
NI Hour;
NI Monthday;
NU8 Month;
NI Year;
NU8 Weekday;
NI Yearday;
NIM_BOOL Isdst;
NimStringDesc* Tzname;
NI Timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY101854[7];
struct TY101352 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY101875[7];
typedef NimStringDesc* TY103039[7];
typedef NimStringDesc* TY103055[12];
struct  slice84465  {
NI A;
NI B;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  tcell45135  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45151  {
NI Len;
NI Cap;
tcell45135** D;
};
struct  tcellset45147  {
NI Counter;
NI Max;
tpagedesc45143* Head;
tpagedesc45143** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45151 Zct;
tcellseq45151 Decstack;
tcellset45147 Cycleroots;
tcellseq45151 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47214 Stat;
};
typedef NI TY26620[8];
struct  tpagedesc45143  {
tpagedesc45143* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
N_NIMCALL(time_t, fromseconds_101279)(NI64 since1970);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(timeinterval101207, initinterval_101414)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(NIM_BOOL, isleapyear_101430)(NI year);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, getdaysinmonth_101445)(NU8 month, NI year);
static N_INLINE(void, HEX2BHEX3D_101493)(NF* x_101499, NF y_101502);
N_NIMCALL(NF, toseconds_101458)(timeinfo101205* a, timeinterval101207* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NF, HEX2F_84403)(NI x, NI y);
N_NIMCALL(void, HEX2B_101633)(timeinfo101205* a, timeinterval101207* interval, timeinfo101205* Result);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_101646)(timeinfo101205* a, timeinterval101207* interval, timeinfo101205* Result);
N_NIMCALL(void, tmtotimeinfo_101848)(struct tm* tm, NIM_BOOL local, timeinfo101205* Result);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, gettzname_101350)(TY101352* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_101404)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_101870)(timeinfo101205* t);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_101409)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NIMCALL(time_t, gettime_101250)(void);
N_NIMCALL(void, getlocaltime_101255)(time_t t, timeinfo101205* Result);
N_NIMCALL(void, getgmtime_101261)(time_t t, timeinfo101205* Result);
N_NIMCALL(time_t, timeinfototime_101267)(timeinfo101205* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_102437)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_101296)(timeinfo101205* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_101302)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_102483)(time_t t);
N_NIMCALL(NI64, mulInt64)(NI64 a, NI64 b);
static N_INLINE(NI64, addInt64)(NI64 a, NI64 b);
N_NIMCALL(time_t, wintimetounixtime_102491)(NI64 t);
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b);
static N_INLINE(NI64, divInt64)(NI64 a, NI64 b);
N_NIMCALL(time_t, fromseconds_101273)(NF since1970);
N_NIMCALL(NF, toseconds_101290)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_103034)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_103050)(NU8 m);
N_NIMCALL(void, formattoken_103066)(timeinfo101205* info, NimStringDesc* token, NimStringDesc** buf);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_84458)(NimStringDesc* s, slice84465 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75028, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(slice84465, HEX2EHEX2E_90099)(NI a_90103, NI b_90105);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c);
N_NIMCALL(void, insert_86201)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45135*, usrtocell_48846)(void* usr);
static N_INLINE(void, rtladdzct_50404)(tcell45135* c);
N_NOINLINE(void, addzct_48817)(tcellseq45151* s, tcell45135* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_103221)(timeinfo101205* info, NimStringDesc* f);
STRING_LITERAL(TMP163, "UTC", 3);
NIM_CONST TY101854 weekdays_101853 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
NIM_CONST TY101875 weekdays_101874 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP168, "", 0);
STRING_LITERAL(TMP175, "Monday", 6);
STRING_LITERAL(TMP176, "Tuesday", 7);
STRING_LITERAL(TMP177, "Wednesday", 9);
STRING_LITERAL(TMP178, "Thursday", 8);
STRING_LITERAL(TMP179, "Friday", 6);
STRING_LITERAL(TMP180, "Saturday", 8);
STRING_LITERAL(TMP181, "Sunday", 6);
NIM_CONST TY103039 lookup_103038 = {((NimStringDesc*) &TMP175),
((NimStringDesc*) &TMP176),
((NimStringDesc*) &TMP177),
((NimStringDesc*) &TMP178),
((NimStringDesc*) &TMP179),
((NimStringDesc*) &TMP180),
((NimStringDesc*) &TMP181)}
;
STRING_LITERAL(TMP182, "January", 7);
STRING_LITERAL(TMP183, "February", 8);
STRING_LITERAL(TMP184, "March", 5);
STRING_LITERAL(TMP185, "April", 5);
STRING_LITERAL(TMP186, "May", 3);
STRING_LITERAL(TMP187, "June", 4);
STRING_LITERAL(TMP188, "July", 4);
STRING_LITERAL(TMP189, "August", 6);
STRING_LITERAL(TMP190, "September", 9);
STRING_LITERAL(TMP191, "October", 7);
STRING_LITERAL(TMP192, "November", 8);
STRING_LITERAL(TMP193, "December", 8);
NIM_CONST TY103055 lookup_103054 = {((NimStringDesc*) &TMP182),
((NimStringDesc*) &TMP183),
((NimStringDesc*) &TMP184),
((NimStringDesc*) &TMP185),
((NimStringDesc*) &TMP186),
((NimStringDesc*) &TMP187),
((NimStringDesc*) &TMP188),
((NimStringDesc*) &TMP189),
((NimStringDesc*) &TMP190),
((NimStringDesc*) &TMP191),
((NimStringDesc*) &TMP192),
((NimStringDesc*) &TMP193)}
;
STRING_LITERAL(TMP194, "d", 1);
STRING_LITERAL(TMP195, "dd", 2);
STRING_LITERAL(TMP196, "ddd", 3);
STRING_LITERAL(TMP197, "dddd", 4);
STRING_LITERAL(TMP198, "h", 1);
STRING_LITERAL(TMP199, "hh", 2);
STRING_LITERAL(TMP200, "H", 1);
STRING_LITERAL(TMP201, "HH", 2);
STRING_LITERAL(TMP202, "m", 1);
STRING_LITERAL(TMP203, "mm", 2);
STRING_LITERAL(TMP204, "M", 1);
STRING_LITERAL(TMP205, "MM", 2);
STRING_LITERAL(TMP206, "MMM", 3);
STRING_LITERAL(TMP207, "MMMM", 4);
STRING_LITERAL(TMP208, "s", 1);
STRING_LITERAL(TMP209, "ss", 2);
STRING_LITERAL(TMP210, "t", 1);
STRING_LITERAL(TMP211, "tt", 2);
STRING_LITERAL(TMP212, "y", 1);
STRING_LITERAL(TMP213, "yy", 2);
STRING_LITERAL(TMP214, "yyy", 3);
STRING_LITERAL(TMP215, "yyyy", 4);
STRING_LITERAL(TMP216, "yyyyy", 5);
STRING_LITERAL(TMP217, "z", 1);
STRING_LITERAL(TMP218, "zz", 2);
STRING_LITERAL(TMP219, "zzz", 3);
STRING_LITERAL(TMP220, "ZZZ", 3);
STRING_LITERAL(TMP221, "0", 1);
STRING_LITERAL(TMP228, "PM", 2);
STRING_LITERAL(TMP229, "AM", 2);
STRING_LITERAL(TMP253, ":00", 3);
STRING_LITERAL(TMP256, "Invalid format string: ", 23);
extern TFrame* frameptr_16242;
extern TNimType NTI3211; /* RootObj */
TNimType NTI101205; /* TimeInfo */
extern TNimType NTI108; /* int */
TNimType NTI101208; /* range 0..61(int) */
TNimType NTI101211; /* range 0..59(int) */
TNimType NTI101213; /* range 0..23(int) */
TNimType NTI101216; /* range 1..31(int) */
TNimType NTI101006; /* Month */
TNimType NTI101220; /* range -10000..10000(int) */
TNimType NTI101008; /* WeekDay */
TNimType NTI101226; /* range 0..365(int) */
extern TNimType NTI138; /* bool */
extern TNimType NTI149; /* string */
extern TNimType NTI21601; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern tgcheap47216 gch_47244;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(time_t, fromseconds_101279)(NI64 since1970) {
	time_t result;
	nimfr("fromSeconds", "times.nim")
	result = 0;
	nimln(164, "times.nim");
	nimln(166, "times.nim");
	result = fromseconds_101273(((NF) (since1970)));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	nimfr("<", "times.nim")
	result = 0;
	nimln(183, "times.nim");
	nimln(183, "times.nim");
	nimln(183, "times.nim");
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < IL64(0));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	nimfr("<=", "times.nim")
	result = 0;
	nimln(188, "times.nim");
	nimln(188, "times.nim");
	nimln(188, "times.nim");
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= IL64(0));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	nimfr("==", "times.nim")
	result = 0;
	nimln(193, "times.nim");
	nimln(193, "times.nim");
	nimln(193, "times.nim");
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == IL64(0));
	popFrame();
	return result;
}

N_NIMCALL(timeinterval101207, initinterval_101414)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	timeinterval101207 result;
	nimfr("initInterval", "times.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(211, "times.nim");
	result.Miliseconds = miliseconds;
	nimln(212, "times.nim");
	result.Seconds = seconds;
	nimln(213, "times.nim");
	result.Minutes = minutes;
	nimln(214, "times.nim");
	result.Hours = hours;
	nimln(215, "times.nim");
	result.Days = days;
	nimln(216, "times.nim");
	result.Months = months;
	nimln(217, "times.nim");
	result.Years = years;
	popFrame();
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI64)(a % b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_101430)(NI year) {
	NIM_BOOL result;
	nimfr("isLeapYear", "times.nim")
	result = 0;
	nimln(222, "times.nim");
	{
		NI TMP143;
		nimln(222, "times.nim");
		nimln(222, "times.nim");
		TMP143 = modInt(year, 400);
		if (!(((NI) ((NI64)(TMP143))) == 0)) goto LA3;
		nimln(223, "times.nim");
		nimln(223, "times.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP144;
		nimln(224, "times.nim");
		nimln(224, "times.nim");
		TMP144 = modInt(year, 100);
		if (!(((NI) ((NI64)(TMP144))) == 0)) goto LA6;
		nimln(225, "times.nim");
		nimln(225, "times.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		NI TMP145;
		nimln(226, "times.nim");
		nimln(226, "times.nim");
		TMP145 = modInt(year, 4);
		if (!(((NI) ((NI64)(TMP145))) == 0)) goto LA9;
		nimln(227, "times.nim");
		nimln(227, "times.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		nimln(229, "times.nim");
		nimln(229, "times.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, getdaysinmonth_101445)(NU8 month, NI year) {
	NI result;
	nimfr("getDaysInMonth", "times.nim")
	result = 0;
	nimln(235, "times.nim");
	switch (month) {
	case ((NU8) 1):
	{
		nimln(236, "times.nim");
		nimln(236, "times.nim");
		{
			NIM_BOOL LOC4;
			nimln(236, "times.nim");
			LOC4 = 0;
			LOC4 = isleapyear_101430(year);
			if (!LOC4) goto LA5;
			result = 29;
		}
		goto LA2;
		LA5: ;
		{
			result = 28;
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		nimln(237, "times.nim");
		result = 30;
	}
	break;
	default:
	{
		nimln(238, "times.nim");
		result = 31;
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(void, HEX2BHEX3D_101493)(NF* x_101499, NF y_101502) {
	nimfr("+=", "system.nim")
	nimln(2893, "system.nim");
	nimln(2893, "system.nim");
	(*x_101499) = ((NF)((*x_101499)) + (NF)(y_101502));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NF, HEX2F_84403)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_101458)(timeinfo101205* a, timeinterval101207* interval) {
	NF result;
	timeinfo101205 anew;
	timeinterval101207 newinterv;
	NI TMP153;
	NU8 curmonth;
	NI TMP157;
	NI TMP158;
	NI TMP159;
	NI TMP160;
	NI TMP161;
	NI TMP162;
	NF LOC10;
	nimfr("toSeconds", "times.nim")
	result = 0;
	memset((void*)(&anew), 0, sizeof(anew));
	anew.Sup.m_type = (&NTI101205);
	nimln(244, "times.nim");
	genericAssign((void*)(&anew), (void*)a, (&NTI101205));
	nimln(245, "times.nim");
	newinterv = (*interval);
	nimln(246, "times.nim");
	result = 0.0;
	nimln(248, "times.nim");
	nimln(248, "times.nim");
	TMP153 = mulInt((*interval).Years, 12);
	newinterv.Months = addInt(newinterv.Months, (NI64)(TMP153));
	nimln(249, "times.nim");
	curmonth = anew.Month;
	{
		NI mth_101488;
		NI HEX3Atmp_101609;
		NI res_101612;
		mth_101488 = 0;
		HEX3Atmp_101609 = 0;
		nimln(250, "times.nim");
		HEX3Atmp_101609 = newinterv.Months;
		nimln(1576, "system.nim");
		res_101612 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				NI LOC4;
				NI TMP154;
				NI TMP155;
				NI TMP156;
				nimln(1577, "system.nim");
				if (!(res_101612 <= HEX3Atmp_101609)) goto LA3;
				nimln(1576, "system.nim");
				mth_101488 = res_101612;
				nimln(251, "times.nim");
				nimln(251, "times.nim");
				nimln(251, "times.nim");
				nimln(251, "times.nim");
				nimln(251, "times.nim");
				LOC4 = 0;
				LOC4 = getdaysinmonth_101445(curmonth, ((NI) (anew.Year)));
				TMP154 = mulInt(LOC4, 24);
				TMP155 = mulInt((NI64)(TMP154), 60);
				TMP156 = mulInt((NI64)(TMP155), 60);
				HEX2BHEX3D_101493((&result), ((NF) ((NI64)(TMP156))));
				nimln(252, "times.nim");
				{
					nimln(252, "times.nim");
					if (!(curmonth == ((NU8) 11))) goto LA7;
					nimln(253, "times.nim");
					curmonth = ((NU8) 0);
					nimln(254, "times.nim");
					anew.Year = addInt(anew.Year, 1);
				}
				goto LA5;
				LA7: ;
				{
					nimln(256, "times.nim");
					curmonth = addInt(curmonth, 1);
				}
				LA5: ;
				nimln(1579, "system.nim");
				res_101612 = addInt(res_101612, 1);
			} LA3: ;
		}
	}
	nimln(257, "times.nim");
	nimln(257, "times.nim");
	nimln(257, "times.nim");
	nimln(257, "times.nim");
	TMP157 = mulInt(newinterv.Days, 24);
	TMP158 = mulInt((NI64)(TMP157), 60);
	TMP159 = mulInt((NI64)(TMP158), 60);
	HEX2BHEX3D_101493((&result), ((NF) ((NI64)(TMP159))));
	nimln(258, "times.nim");
	nimln(258, "times.nim");
	nimln(258, "times.nim");
	TMP160 = mulInt(newinterv.Hours, 60);
	TMP161 = mulInt((NI64)(TMP160), 60);
	HEX2BHEX3D_101493((&result), ((NF) ((NI64)(TMP161))));
	nimln(259, "times.nim");
	nimln(259, "times.nim");
	TMP162 = mulInt(newinterv.Minutes, 60);
	HEX2BHEX3D_101493((&result), ((NF) ((NI64)(TMP162))));
	nimln(260, "times.nim");
	HEX2BHEX3D_101493((&result), ((NF) (newinterv.Seconds)));
	nimln(261, "times.nim");
	nimln(261, "times.nim");
	LOC10 = 0;
	LOC10 = HEX2F_84403(newinterv.Miliseconds, 1000);
	HEX2BHEX3D_101493((&result), LOC10);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2B_101633)(timeinfo101205* a, timeinterval101207* interval, timeinfo101205* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	nimfr("+", "times.nim")
	nimln(268, "times.nim");
	nimln(268, "times.nim");
	LOC1 = 0;
	LOC1 = timeinfototime_101267(a);
	t = toseconds_101290(LOC1);
	nimln(269, "times.nim");
	secs = toseconds_101458(a, interval);
	nimln(270, "times.nim");
	{
		time_t LOC6;
		nimln(270, "times.nim");
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP163))) goto LA4;
		nimln(271, "times.nim");
		nimln(271, "times.nim");
		nimln(271, "times.nim");
		LOC6 = 0;
		LOC6 = fromseconds_101273(((NF)(t) + (NF)(secs)));
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI101205));
		(*Result).Sup.m_type = (&NTI101205);
		getgmtime_101261(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		nimln(273, "times.nim");
		nimln(273, "times.nim");
		nimln(273, "times.nim");
		LOC8 = 0;
		LOC8 = fromseconds_101273(((NF)(t) + (NF)(secs)));
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI101205));
		(*Result).Sup.m_type = (&NTI101205);
		getlocaltime_101255(LOC8, Result);
	}
	LA2: ;
	popFrame();
}

N_NIMCALL(void, HEX2D_101646)(timeinfo101205* a, timeinterval101207* interval, timeinfo101205* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	nimfr("-", "times.nim")
	nimln(280, "times.nim");
	nimln(280, "times.nim");
	LOC1 = 0;
	LOC1 = timeinfototime_101267(a);
	t = toseconds_101290(LOC1);
	nimln(281, "times.nim");
	secs = toseconds_101458(a, interval);
	nimln(282, "times.nim");
	{
		time_t LOC6;
		nimln(282, "times.nim");
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP163))) goto LA4;
		nimln(283, "times.nim");
		nimln(283, "times.nim");
		nimln(283, "times.nim");
		LOC6 = 0;
		LOC6 = fromseconds_101273(((NF)(t) - (NF)(secs)));
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI101205));
		(*Result).Sup.m_type = (&NTI101205);
		getgmtime_101261(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		nimln(285, "times.nim");
		nimln(285, "times.nim");
		nimln(285, "times.nim");
		LOC8 = 0;
		LOC8 = fromseconds_101273(((NF)(t) - (NF)(secs)));
		chckNil((void*)Result);
		genericReset((void*)Result, (&NTI101205));
		(*Result).Sup.m_type = (&NTI101205);
		getlocaltime_101255(LOC8, Result);
	}
	LA2: ;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, gettzname_101350)(TY101352* Result) {
	nimfr("getTzname", "times.nim")
	nimln(446, "times.nim");
	nimln(446, "times.nim");
	nimln(446, "times.nim");
	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(0)- 0]));
	nimln(446, "times.nim");
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(1)- 0]));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(NI, gettimezone_101404)(void) {
	NI result;
	nimfr("getTimezone", "times.nim")
	result = 0;
	nimln(449, "times.nim");
	nimln(449, "times.nim");
	result = timezone;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, tmtotimeinfo_101848)(struct tm* tm, NIM_BOOL local, timeinfo101205* Result) {
	timeinfo101205 LOC1;
	NI TMP164;
	nimfr("tmToTimeInfo", "times.nim")
	nimln(346, "times.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI101205);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI101205);
	LOC1.Second = ((NI)chckRange(((NI) ((*tm).tm_sec)), 0, 61));
	LOC1.Minute = ((NI)chckRange(((NI) ((*tm).tm_min)), 0, 59));
	LOC1.Hour = ((NI)chckRange(((NI) ((*tm).tm_hour)), 0, 23));
	LOC1.Monthday = ((NI)chckRange(((NI) ((*tm).tm_mday)), 1, 31));
	LOC1.Month = ((NU8)chckRange((*tm).tm_mon, ((NU8) 0), ((NU8) 11)));
	nimln(354, "times.nim");
	TMP164 = addInt((*tm).tm_year, ((NI32) 1900));
	if (TMP164 < (-2147483647 -1) || TMP164 > 2147483647) raiseOverflow();
	LOC1.Year = ((NI)chckRange((NI32)(TMP164), -10000, 10000));
	if ((NU)(((NI) ((*tm).tm_wday))) > (NU)(6)) raiseIndexError();
	LOC1.Weekday = weekdays_101853[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.Yearday = ((NI)chckRange(((NI) ((*tm).tm_yday)), 0, 365));
	nimln(357, "times.nim");
	LOC1.Isdst = (((NI32) 0) < (*tm).tm_isdst);
	nimln(358, "times.nim");
	{
		if (!local) goto LA4;
		nimln(359, "times.nim");
		{
			TY101352 LOC10;
			nimln(359, "times.nim");
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			nimln(360, "times.nim");
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_101350((&LOC10));
			LOC1.Tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY101352 LOC12;
			nimln(362, "times.nim");
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_101350((&LOC12));
			LOC1.Tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.Tzname = copyString(((NimStringDesc*) &TMP163));
	}
	LA2: ;
	nimln(365, "times.nim");
	{
		if (!local) goto LA16;
		nimln(365, "times.nim");
		LOC1.Timezone = gettimezone_101404();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.Timezone = 0;
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI101205));
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(struct tm, timeinfototm_101870)(timeinfo101205* t) {
	struct tm result;
	NI TMP165;
	NI LOC1;
	nimfr("timeInfoToTM", "times.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(371, "times.nim");
	result.tm_sec = ((int) ((*t).Second));
	nimln(372, "times.nim");
	result.tm_min = ((int) ((*t).Minute));
	nimln(373, "times.nim");
	result.tm_hour = ((int) ((*t).Hour));
	nimln(374, "times.nim");
	result.tm_mday = ((int) ((*t).Monthday));
	nimln(375, "times.nim");
	nimln(375, "times.nim");
	result.tm_mon = ((int) ((*t).Month));
	nimln(376, "times.nim");
	nimln(376, "times.nim");
	TMP165 = subInt(((NI) ((*t).Year)), 1900);
	result.tm_year = ((int) ((NI64)(TMP165)));
	nimln(377, "times.nim");
	result.tm_wday = ((int) (weekdays_101874[((*t).Weekday)- 0]));
	nimln(378, "times.nim");
	result.tm_yday = ((int) ((*t).Yearday));
	nimln(379, "times.nim");
	LOC1 = 0;
	nimln(379, "times.nim");
	{
		if (!(*t).Isdst) goto LA4;
		LOC1 = 1;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = 0;
	}
	LA2: ;
	result.tm_isdst = ((int)chckRange(LOC1, ((int) (-2147483647 -1)), ((int) 2147483647)));
	popFrame();
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
	nimfr("-", "times.nim")
	result = 0;
	nimln(383, "times.nim");
	nimln(383, "times.nim");
	nimln(383, "times.nim");
	nimln(383, "times.nim");
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_101409)(void) {
	NI result;
	NI LOC1;
	NI TMP166;
	NI TMP167;
	nimfr("getStartMilsecs", "times.nim")
	result = 0;
	nimln(391, "times.nim");
	nimln(391, "times.nim");
	nimln(391, "times.nim");
	LOC1 = 0;
	LOC1 = clock();
	nimln(391, "times.nim");
	TMP166 = divInt(CLOCKS_PER_SEC, 1000);
	TMP167 = divInt(LOC1, (NI64)(TMP166));
	result = (NI64)(TMP167);
	popFrame();
	return result;
}

N_NIMCALL(time_t, gettime_101250)(void) {
	time_t result;
	nimfr("getTime", "times.nim")
	result = 0;
	nimln(398, "times.nim");
	nimln(398, "times.nim");
	result = time(NIM_NIL);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, getlocaltime_101255)(time_t t, timeinfo101205* Result) {
	time_t a;
	struct tm* LOC1;
	nimfr("getLocalTime", "times.nim")
	nimln(400, "times.nim");
	a = t;
	nimln(401, "times.nim");
	nimln(401, "times.nim");
	LOC1 = 0;
	LOC1 = localtime((&a));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI101205));
	(*Result).Sup.m_type = (&NTI101205);
	tmtotimeinfo_101848((&(*LOC1)), NIM_TRUE, Result);
	popFrame();
}

N_NIMCALL(void, getgmtime_101261)(time_t t, timeinfo101205* Result) {
	time_t a;
	struct tm* LOC1;
	nimfr("getGMTime", "times.nim")
	nimln(406, "times.nim");
	a = t;
	nimln(407, "times.nim");
	nimln(407, "times.nim");
	LOC1 = 0;
	LOC1 = gmtime((&a));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI101205));
	(*Result).Sup.m_type = (&NTI101205);
	tmtotimeinfo_101848((&(*LOC1)), NIM_FALSE, Result);
	popFrame();
}

N_NIMCALL(time_t, timeinfototime_101267)(timeinfo101205* timeinfo) {
	time_t result;
	timeinfo101205 ctimeinfo;
	struct tm LOC1;
	nimfr("timeInfoToTime", "times.nim")
	result = 0;
	memset((void*)(&ctimeinfo), 0, sizeof(ctimeinfo));
	ctimeinfo.Sup.m_type = (&NTI101205);
	nimln(412, "times.nim");
	genericAssign((void*)(&ctimeinfo), (void*)timeinfo, (&NTI101205));
	nimln(414, "times.nim");
	nimln(414, "times.nim");
	nimln(414, "times.nim");
	LOC1 = timeinfototm_101870((&ctimeinfo));
	result = mktime((&LOC1));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_102437)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	nimfr("toStringTillNL", "times.nim")
	result = 0;
	nimln(417, "times.nim");
	result = copyString(((NimStringDesc*) &TMP168));
	nimln(418, "times.nim");
	i = 0;
	{
		nimln(419, "times.nim");
		while (1) {
			NIM_BOOL LOC3;
			NIM_BOOL LOC4;
			nimln(419, "times.nim");
			LOC3 = 0;
			nimln(419, "times.nim");
			LOC4 = 0;
			nimln(419, "times.nim");
			nimln(419, "times.nim");
			LOC4 = !(((NU8)(p[i]) == (NU8)(0)));
			if (!(LOC4)) goto LA5;
			nimln(419, "times.nim");
			nimln(419, "times.nim");
			LOC4 = !(((NU8)(p[i]) == (NU8)(10)));
			LA5: ;
			LOC3 = LOC4;
			if (!(LOC3)) goto LA6;
			nimln(419, "times.nim");
			nimln(419, "times.nim");
			LOC3 = !(((NU8)(p[i]) == (NU8)(13)));
			LA6: ;
			if (!LOC3) goto LA2;
			nimln(420, "times.nim");
			result = addChar(result, p[i]);
			nimln(421, "times.nim");
			i = addInt(i, 1);
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_101296)(timeinfo101205* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	nimfr("$", "times.nim")
	result = 0;
	nimln(425, "times.nim");
	nimln(425, "times.nim");
	LOC1 = timeinfototm_101870(timeinfo);
	p = asctime((&LOC1));
	nimln(426, "times.nim");
	result = tostringtillnl_102437(p);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_101302)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
	nimfr("$", "times.nim")
	result = 0;
	nimln(430, "times.nim");
	a = time;
	nimln(431, "times.nim");
	nimln(431, "times.nim");
	nimln(431, "times.nim");
	LOC1 = 0;
	LOC1 = ctime((&a));
	result = tostringtillnl_102437(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, addInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	result = (NI64)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (IL64(0) <= (NI64)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (IL64(0) <= (NI64)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_102483)(time_t t) {
	NI64 result;
	NI64 TMP169;
	NI64 TMP170;
	nimfr("unixTimeToWinTime", "times.nim")
	result = 0;
	nimln(439, "times.nim");
	nimln(439, "times.nim");
	nimln(439, "times.nim");
	TMP169 = mulInt64(((NI64) (t)), IL64(10000000));
	TMP170 = addInt64((NI64)(TMP169), IL64(116444736000000000));
	result = (NI64)(TMP170);
	popFrame();
	return result;
}

static N_INLINE(NI64, subInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	result = (NI64)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (IL64(0) <= (NI64)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (IL64(0) <= (NI64)(result ^ (NI64)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI64, divInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	{
		if (!(b == IL64(0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == IL64(-1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_102491)(NI64 t) {
	time_t result;
	NI64 TMP171;
	NI64 TMP172;
	nimfr("winTimeToUnixTime", "times.nim")
	result = 0;
	nimln(443, "times.nim");
	nimln(443, "times.nim");
	nimln(443, "times.nim");
	TMP171 = subInt64(t, IL64(116444736000000000));
	TMP172 = divInt64((NI64)(TMP171), IL64(10000000));
	result = ((time_t) ((NI64)(TMP172)));
	popFrame();
	return result;
}

N_NIMCALL(time_t, fromseconds_101273)(NF since1970) {
	time_t result;
	nimfr("fromSeconds", "times.nim")
	result = 0;
	nimln(451, "times.nim");
	result = ((time_t) (since1970));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_101290)(time_t time) {
	NF result;
	nimfr("toSeconds", "times.nim")
	result = 0;
	nimln(453, "times.nim");
	result = ((NF) (time));
	popFrame();
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	struct timeval a;
	nimfr("epochTime", "times.nim")
	result = 0;
	memset((void*)(&a), 0, sizeof(a));
	nimln(459, "times.nim");
	gettimeofday((&a), NIM_NIL);
	nimln(460, "times.nim");
	nimln(460, "times.nim");
	nimln(460, "times.nim");
	nimln(460, "times.nim");
	nimln(460, "times.nim");
	result = ((NF)(((double) (a.tv_sec))) + (NF)(((NF)(((double) (a.tv_usec))) * (NF)(9.9999999999999995e-07))));
	popFrame();
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	nimfr("cpuTime", "times.nim")
	result = 0;
	nimln(472, "times.nim");
	nimln(472, "times.nim");
	nimln(472, "times.nim");
	nimln(472, "times.nim");
	LOC1 = 0;
	LOC1 = clock();
	nimln(472, "times.nim");
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	timeinfo101205 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NI TMP174;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("getDateStr", "times.nim")
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI101205);
	nimln(540, "times.nim");
	nimln(540, "times.nim");
	LOC1 = 0;
	LOC1 = gettime_101250();
	chckNil((void*)(&ti));
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI101205);
	getlocaltime_101255(LOC1, (&ti));
	nimln(541, "times.nim");
	nimln(542, "times.nim");
	LOC2 = 0;
	nimln(541, "times.nim");
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (ti.Year)));
	nimln(541, "times.nim");
	nimln(541, "times.nim");
	nimln(541, "times.nim");
	TMP174 = addInt(((NI) (ti.Month)), 1);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI64)(TMP174))), 2);
	nimln(542, "times.nim");
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Monthday)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	timeinfo101205 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("getClockStr", "times.nim")
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI101205);
	nimln(546, "times.nim");
	nimln(546, "times.nim");
	LOC1 = 0;
	LOC1 = gettime_101250();
	chckNil((void*)(&ti));
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI101205);
	getlocaltime_101255(LOC1, (&ti));
	nimln(547, "times.nim");
	nimln(548, "times.nim");
	LOC2 = 0;
	nimln(547, "times.nim");
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.Hour)), 2);
	nimln(547, "times.nim");
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.Minute)), 2);
	nimln(548, "times.nim");
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Second)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_103034)(NU8 day) {
	NimStringDesc* result;
	nimfr("$", "times.nim")
	result = 0;
	nimln(554, "times.nim");
	nimln(554, "times.nim");
	result = copyString(lookup_103038[(day)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_103050)(NU8 m) {
	NimStringDesc* result;
	nimfr("$", "times.nim")
	result = 0;
	nimln(561, "times.nim");
	nimln(561, "times.nim");
	result = copyString(lookup_103054[(m)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_84458)(NimStringDesc* s, slice84465 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2773, "system.nim");
	nimln(2773, "system.nim");
	LOC1 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP222;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP222 = addInt(s->Sup.len, x.A);
		LOC1 = (NI64)(TMP222);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP223;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP223 = addInt(s->Sup.len, x.B);
		LOC7 = (NI64)(TMP223);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(slice84465, HEX2EHEX2E_90099)(NI a_90103, NI b_90105) {
	slice84465 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_90103;
	nimln(227, "system.nim");
	result.B = b_90105;
	popFrame();
	return result;
}

static N_INLINE(tcell45135*, usrtocell_48846)(void* usr) {
	tcell45135* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45135*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45135))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50404)(tcell45135* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48817((&gch_47244.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45135* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48846(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45135* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48846((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50404(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_103066)(timeinfo101205* info, NimStringDesc* token, NimStringDesc** buf) {
	nimfr("formatToken", "times.nim")
	nimln(569, "times.nim");
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP168))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP203))) goto LA10;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP194))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP211))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP220))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP212))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP198))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP204))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP205))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP209))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP213))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP206))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP219))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP197))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP210))) goto LA17;
break;
	case 20: 
if (eqStrings(token, ((NimStringDesc*) &TMP216))) goto LA23;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP195))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP202))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP208))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP218))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP200))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP201))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP207))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP214))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP217))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP196))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP199))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP215))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		nimln(571, "times.nim");
		nimln(571, "times.nim");
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		nimln(573, "times.nim");
		{
			nimln(573, "times.nim");
			if (!(((NI) ((*info).Monthday)) < 10)) goto LA36;
			nimln(574, "times.nim");
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP221));
		}
		LA36: ;
		nimln(575, "times.nim");
		nimln(575, "times.nim");
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		slice84465 LOC41;
		NimStringDesc* LOC42;
		nimln(577, "times.nim");
		nimln(577, "times.nim");
		nimln(577, "times.nim");
		LOC40 = 0;
		LOC40 = HEX24_103034((*info).Weekday);
		nimln(577, "times.nim");
		LOC41 = HEX2EHEX2E_90099(0, 2);
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_84458(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		nimln(579, "times.nim");
		nimln(579, "times.nim");
		LOC44 = 0;
		LOC44 = HEX24_103034((*info).Weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		nimln(581, "times.nim");
		nimln(581, "times.nim");
		LOC46 = 0;
		nimln(581, "times.nim");
		{
			NI TMP224;
			nimln(581, "times.nim");
			if (!(12 < ((NI) ((*info).Hour)))) goto LA49;
			nimln(581, "times.nim");
			TMP224 = subInt(((NI) ((*info).Hour)), 12);
			LOC46 = ((NI) ((NI64)(TMP224)));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).Hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		nimln(583, "times.nim");
		nimln(583, "times.nim");
		{
			NI TMP225;
			nimln(583, "times.nim");
			if (!(12 < ((NI) ((*info).Hour)))) goto LA56;
			nimln(583, "times.nim");
			TMP225 = subInt(((NI) ((*info).Hour)), 12);
			amerhour = ((NI) ((NI64)(TMP225)));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).Hour));
		}
		LA54: ;
		nimln(584, "times.nim");
		{
			nimln(584, "times.nim");
			if (!(amerhour < 10)) goto LA61;
			nimln(585, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		nimln(586, "times.nim");
		nimln(586, "times.nim");
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		nimln(588, "times.nim");
		nimln(588, "times.nim");
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		nimln(590, "times.nim");
		{
			nimln(590, "times.nim");
			if (!(((NI) ((*info).Hour)) < 10)) goto LA69;
			nimln(591, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		nimln(592, "times.nim");
		nimln(592, "times.nim");
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		nimln(594, "times.nim");
		nimln(594, "times.nim");
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		nimln(596, "times.nim");
		{
			nimln(596, "times.nim");
			if (!(((NI) ((*info).Minute)) < 10)) goto LA77;
			nimln(597, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		nimln(598, "times.nim");
		nimln(598, "times.nim");
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NI TMP226;
		NimStringDesc* LOC81;
		nimln(600, "times.nim");
		nimln(600, "times.nim");
		nimln(600, "times.nim");
		TMP226 = addInt(((NI) ((*info).Month)), 1);
		LOC81 = 0;
		LOC81 = nimIntToStr((NI64)(TMP226));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NI TMP227;
		NimStringDesc* LOC87;
		nimln(602, "times.nim");
		{
			nimln(602, "times.nim");
			if (!((*info).Month < ((NU8) 9))) goto LA85;
			nimln(603, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		nimln(604, "times.nim");
		nimln(604, "times.nim");
		nimln(604, "times.nim");
		TMP227 = addInt(((NI) ((*info).Month)), 1);
		LOC87 = 0;
		LOC87 = nimIntToStr((NI64)(TMP227));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		slice84465 LOC90;
		NimStringDesc* LOC91;
		nimln(606, "times.nim");
		nimln(606, "times.nim");
		nimln(606, "times.nim");
		LOC89 = 0;
		LOC89 = HEX24_103050((*info).Month);
		nimln(606, "times.nim");
		LOC90 = HEX2EHEX2E_90099(0, 2);
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_84458(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		nimln(608, "times.nim");
		nimln(608, "times.nim");
		LOC93 = 0;
		LOC93 = HEX24_103050((*info).Month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		nimln(610, "times.nim");
		nimln(610, "times.nim");
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		nimln(612, "times.nim");
		{
			nimln(612, "times.nim");
			if (!(((NI) ((*info).Second)) < 10)) goto LA99;
			nimln(613, "times.nim");
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		nimln(614, "times.nim");
		nimln(614, "times.nim");
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		nimln(616, "times.nim");
		{
			nimln(616, "times.nim");
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA105;
			nimln(617, "times.nim");
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			nimln(618, "times.nim");
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		nimln(620, "times.nim");
		{
			nimln(620, "times.nim");
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA111;
			nimln(621, "times.nim");
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP228));
		}
		goto LA109;
		LA111: ;
		{
			nimln(622, "times.nim");
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP229));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NI TMP230;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		NI TMP231;
		slice84465 LOC122;
		NimStringDesc* LOC123;
		nimln(624, "times.nim");
		nimln(624, "times.nim");
		nimln(624, "times.nim");
		nimln(624, "times.nim");
		LOC115 = 0;
		LOC115 = nimIntToStr(((NI) ((*info).Year)));
		TMP230 = subInt(LOC115->Sup.len, 1);
		fr = (NI64)(TMP230);
		nimln(625, "times.nim");
		{
			nimln(625, "times.nim");
			if (!(fr < 0)) goto LA118;
			nimln(625, "times.nim");
			fr = 0;
		}
		LA118: ;
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		LOC120 = 0;
		LOC120 = nimIntToStr(((NI) ((*info).Year)));
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		nimln(626, "times.nim");
		LOC121 = 0;
		LOC121 = nimIntToStr(((NI) ((*info).Year)));
		TMP231 = subInt(LOC121->Sup.len, 1);
		LOC122 = HEX2EHEX2E_90099(fr, (NI64)(TMP231));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_84458(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NI TMP232;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		NI TMP233;
		slice84465 LOC132;
		nimln(628, "times.nim");
		nimln(628, "times.nim");
		nimln(628, "times.nim");
		nimln(628, "times.nim");
		LOC125 = 0;
		LOC125 = nimIntToStr(((NI) ((*info).Year)));
		TMP232 = subInt(LOC125->Sup.len, 2);
		fr = (NI64)(TMP232);
		nimln(629, "times.nim");
		{
			nimln(629, "times.nim");
			if (!(fr < 0)) goto LA128;
			nimln(629, "times.nim");
			fr = 0;
		}
		LA128: ;
		nimln(630, "times.nim");
		nimln(630, "times.nim");
		LOC130 = 0;
		LOC130 = nimIntToStr(((NI) ((*info).Year)));
		nimln(630, "times.nim");
		nimln(630, "times.nim");
		nimln(630, "times.nim");
		nimln(630, "times.nim");
		LOC131 = 0;
		LOC131 = nimIntToStr(((NI) ((*info).Year)));
		TMP233 = subInt(LOC131->Sup.len, 1);
		LOC132 = HEX2EHEX2E_90099(fr, (NI64)(TMP233));
		fyear = HEX5BHEX5D_84458(LOC130, LOC132);
		nimln(631, "times.nim");
		{
			NimStringDesc* LOC137;
			NI TMP235;
			NimStringDesc* LOC138;
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			if (!!((fyear->Sup.len == 2))) goto LA135;
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			LOC137 = 0;
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			nimln(631, "times.nim");
			TMP235 = subInt(2, fyear->Sup.len);
			LOC138 = 0;
			LOC138 = nsuRepeatChar((NI64)(TMP235), 48);
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		nimln(632, "times.nim");
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NI TMP236;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		NI TMP237;
		slice84465 LOC147;
		nimln(634, "times.nim");
		nimln(634, "times.nim");
		nimln(634, "times.nim");
		nimln(634, "times.nim");
		LOC140 = 0;
		LOC140 = nimIntToStr(((NI) ((*info).Year)));
		TMP236 = subInt(LOC140->Sup.len, 3);
		fr = (NI64)(TMP236);
		nimln(635, "times.nim");
		{
			nimln(635, "times.nim");
			if (!(fr < 0)) goto LA143;
			nimln(635, "times.nim");
			fr = 0;
		}
		LA143: ;
		nimln(636, "times.nim");
		nimln(636, "times.nim");
		LOC145 = 0;
		LOC145 = nimIntToStr(((NI) ((*info).Year)));
		nimln(636, "times.nim");
		nimln(636, "times.nim");
		nimln(636, "times.nim");
		nimln(636, "times.nim");
		LOC146 = 0;
		LOC146 = nimIntToStr(((NI) ((*info).Year)));
		TMP237 = subInt(LOC146->Sup.len, 1);
		LOC147 = HEX2EHEX2E_90099(fr, (NI64)(TMP237));
		fyear = HEX5BHEX5D_84458(LOC145, LOC147);
		nimln(637, "times.nim");
		{
			NimStringDesc* LOC152;
			NI TMP238;
			NimStringDesc* LOC153;
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			if (!!((fyear->Sup.len == 3))) goto LA150;
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			LOC152 = 0;
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			nimln(637, "times.nim");
			TMP238 = subInt(3, fyear->Sup.len);
			LOC153 = 0;
			LOC153 = nsuRepeatChar((NI64)(TMP238), 48);
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		nimln(638, "times.nim");
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NI TMP239;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		NI TMP240;
		slice84465 LOC162;
		nimln(640, "times.nim");
		nimln(640, "times.nim");
		nimln(640, "times.nim");
		nimln(640, "times.nim");
		LOC155 = 0;
		LOC155 = nimIntToStr(((NI) ((*info).Year)));
		TMP239 = subInt(LOC155->Sup.len, 4);
		fr = (NI64)(TMP239);
		nimln(641, "times.nim");
		{
			nimln(641, "times.nim");
			if (!(fr < 0)) goto LA158;
			nimln(641, "times.nim");
			fr = 0;
		}
		LA158: ;
		nimln(642, "times.nim");
		nimln(642, "times.nim");
		LOC160 = 0;
		LOC160 = nimIntToStr(((NI) ((*info).Year)));
		nimln(642, "times.nim");
		nimln(642, "times.nim");
		nimln(642, "times.nim");
		nimln(642, "times.nim");
		LOC161 = 0;
		LOC161 = nimIntToStr(((NI) ((*info).Year)));
		TMP240 = subInt(LOC161->Sup.len, 1);
		LOC162 = HEX2EHEX2E_90099(fr, (NI64)(TMP240));
		fyear = HEX5BHEX5D_84458(LOC160, LOC162);
		nimln(643, "times.nim");
		{
			NimStringDesc* LOC167;
			NI TMP241;
			NimStringDesc* LOC168;
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			if (!!((fyear->Sup.len == 4))) goto LA165;
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			LOC167 = 0;
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			nimln(643, "times.nim");
			TMP241 = subInt(4, fyear->Sup.len);
			LOC168 = 0;
			LOC168 = nsuRepeatChar((NI64)(TMP241), 48);
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		nimln(644, "times.nim");
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NI TMP242;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		NI TMP243;
		slice84465 LOC177;
		nimln(646, "times.nim");
		nimln(646, "times.nim");
		nimln(646, "times.nim");
		nimln(646, "times.nim");
		LOC170 = 0;
		LOC170 = nimIntToStr(((NI) ((*info).Year)));
		TMP242 = subInt(LOC170->Sup.len, 5);
		fr = (NI64)(TMP242);
		nimln(647, "times.nim");
		{
			nimln(647, "times.nim");
			if (!(fr < 0)) goto LA173;
			nimln(647, "times.nim");
			fr = 0;
		}
		LA173: ;
		nimln(648, "times.nim");
		nimln(648, "times.nim");
		LOC175 = 0;
		LOC175 = nimIntToStr(((NI) ((*info).Year)));
		nimln(648, "times.nim");
		nimln(648, "times.nim");
		nimln(648, "times.nim");
		nimln(648, "times.nim");
		LOC176 = 0;
		LOC176 = nimIntToStr(((NI) ((*info).Year)));
		TMP243 = subInt(LOC176->Sup.len, 1);
		LOC177 = HEX2EHEX2E_90099(fr, (NI64)(TMP243));
		fyear = HEX5BHEX5D_84458(LOC175, LOC177);
		nimln(649, "times.nim");
		{
			NimStringDesc* LOC182;
			NI TMP244;
			NimStringDesc* LOC183;
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			if (!!((fyear->Sup.len == 5))) goto LA180;
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			LOC182 = 0;
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			nimln(649, "times.nim");
			TMP244 = subInt(5, fyear->Sup.len);
			LOC183 = 0;
			LOC183 = nsuRepeatChar((NI64)(TMP244), 48);
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		nimln(650, "times.nim");
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NI TMP245;
		NI TMP246;
		NimStringDesc* LOC185;
		nimln(652, "times.nim");
		nimln(652, "times.nim");
		nimln(652, "times.nim");
		TMP245 = divInt((*info).Timezone, 60);
		TMP246 = divInt((NI64)(TMP245), 60);
		hrs = (NI64)(TMP246);
		nimln(653, "times.nim");
		nimln(653, "times.nim");
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NI TMP247;
		NI TMP248;
		NimStringDesc* LOC187;
		nimln(655, "times.nim");
		nimln(655, "times.nim");
		nimln(655, "times.nim");
		TMP247 = divInt((*info).Timezone, 60);
		TMP248 = divInt((NI64)(TMP247), 60);
		hrs = (NI64)(TMP248);
		nimln(657, "times.nim");
		nimln(657, "times.nim");
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		nimln(658, "times.nim");
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			NI TMP249;
			NI TMP250;
			nimln(658, "times.nim");
			nimln(658, "times.nim");
			if (hrs == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA190;
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			nimln(659, "times.nim");
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			nimln(659, "times.nim");
			{
				nimln(659, "times.nim");
				if (!(hrs < 0)) goto LA196;
				LOC193 = 1;
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = 0;
			}
			LA194: ;
			TMP249 = subInt(LOC192->Sup.len, LOC193);
			TMP250 = subInt((*buf)->Sup.len, (NI64)(TMP249));
			atindex = (NI64)(TMP250);
			nimln(660, "times.nim");
			insert_86201(buf, ((NimStringDesc*) &TMP221), atindex);
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NI TMP251;
		NI TMP252;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		nimln(662, "times.nim");
		nimln(662, "times.nim");
		nimln(662, "times.nim");
		TMP251 = divInt((*info).Timezone, 60);
		TMP252 = divInt((NI64)(TMP251), 60);
		hrs = (NI64)(TMP252);
		nimln(664, "times.nim");
		nimln(664, "times.nim");
		LOC200 = 0;
		nimln(664, "times.nim");
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP253));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		nimln(665, "times.nim");
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			NI TMP254;
			NI TMP255;
			nimln(665, "times.nim");
			nimln(665, "times.nim");
			if (hrs == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA204;
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			nimln(666, "times.nim");
			LOC206 = 0;
			nimln(666, "times.nim");
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP253));
			LOC208 = 0;
			nimln(666, "times.nim");
			{
				nimln(666, "times.nim");
				if (!(hrs < 0)) goto LA211;
				LOC208 = 1;
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = 0;
			}
			LA209: ;
			TMP254 = subInt(LOC206->Sup.len, LOC208);
			TMP255 = subInt((*buf)->Sup.len, (NI64)(TMP254));
			atindex = (NI64)(TMP255);
			nimln(667, "times.nim");
			insert_86201(buf, ((NimStringDesc*) &TMP221), atindex);
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		nimln(669, "times.nim");
		(*buf) = resizeString((*buf), (*info).Tzname->Sup.len + 0);
appendString((*buf), (*info).Tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		valueerror3249* e_103194;
		NimStringDesc* LOC217;
		e_103194 = 0;
		nimln(2149, "system.nim");
		e_103194 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
		(*e_103194).Sup.Sup.m_type = (&NTI3249);
		nimln(2150, "system.nim");
		nimln(673, "times.nim");
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP256));
appendString(LOC217, token);
		asgnRefNoCycle((void**) (&(*e_103194).Sup.message), LOC217);
		nimln(673, "times.nim");
		raiseException((Exception*)e_103194, "ValueError");
	}
	LA30: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, format_103221)(timeinfo101205* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	nimfr("format", "times.nim")
	result = 0;
	nimln(716, "times.nim");
	result = copyString(((NimStringDesc*) &TMP168));
	nimln(717, "times.nim");
	i = 0;
	nimln(718, "times.nim");
	currentf = copyString(((NimStringDesc*) &TMP168));
	{
		nimln(719, "times.nim");
		while (1) {
			nimln(720, "times.nim");
			if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
			switch (((NU8)(f->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				nimln(722, "times.nim");
				formattoken_103066(info, currentf, (&result));
				nimln(724, "times.nim");
				currentf = copyString(((NimStringDesc*) &TMP168));
				nimln(725, "times.nim");
				{
					nimln(725, "times.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA6;
					nimln(725, "times.nim");
					goto LA1;
				}
				LA6: ;
				nimln(727, "times.nim");
				{
					nimln(727, "times.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA10;
					nimln(728, "times.nim");
					i = addInt(i, 1);
					{
						nimln(729, "times.nim");
						while (1) {
							NIM_BOOL LOC14;
							NI TMP257;
							nimln(729, "times.nim");
							LOC14 = 0;
							nimln(729, "times.nim");
							nimln(729, "times.nim");
							if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
							LOC14 = !(((NU8)(f->data[i]) == (NU8)(39)));
							if (!(LOC14)) goto LA15;
							nimln(729, "times.nim");
							nimln(729, "times.nim");
							nimln(729, "times.nim");
							TMP257 = subInt(f->Sup.len, 1);
							LOC14 = (i < (NI64)(TMP257));
							LA15: ;
							if (!LOC14) goto LA13;
							nimln(730, "times.nim");
							if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
							result = addChar(result, f->data[i]);
							nimln(731, "times.nim");
							i = addInt(i, 1);
						} LA13: ;
					}
				}
				goto LA8;
				LA10: ;
				{
					nimln(732, "times.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					result = addChar(result, f->data[i]);
				}
				LA8: ;
			}
			break;
			default:
			{
				nimln(736, "times.nim");
				{
					NIM_BOOL LOC20;
					nimln(736, "times.nim");
					LOC20 = 0;
					nimln(736, "times.nim");
					nimln(736, "times.nim");
					LOC20 = (currentf->Sup.len < 1);
					if (LOC20) goto LA21;
					nimln(736, "times.nim");
					nimln(736, "times.nim");
					if ((NU)((currentf->Sup.len-1)) > (NU)(currentf->Sup.len)) raiseIndexError();
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					LOC20 = ((NU8)(currentf->data[(currentf->Sup.len-1)]) == (NU8)(f->data[i]));
					LA21: ;
					if (!LOC20) goto LA22;
					nimln(737, "times.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					currentf = addChar(currentf, f->data[i]);
				}
				goto LA18;
				LA22: ;
				{
					nimln(739, "times.nim");
					formattoken_103066(info, currentf, (&result));
					nimln(740, "times.nim");
					i = subInt(i, 1);
					nimln(741, "times.nim");
					currentf = copyString(((NimStringDesc*) &TMP168));
				}
				LA18: ;
			}
			break;
			}
			nimln(743, "times.nim");
			i = addInt(i, 1);
		}
	} LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit)(void) {
	nimfr("times", "times.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit)(void) {
static TNimNode* TMP146[11];
static TNimNode* TMP147[12];
NI TMP149;
static char* NIM_CONST TMP148[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP150[7];
NI TMP152;
static char* NIM_CONST TMP151[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP141[33];
NTI101205.size = sizeof(timeinfo101205);
NTI101205.kind = 17;
NTI101205.base = (&NTI3211);
TMP146[0] = &TMP141[1];
NTI101208.size = sizeof(NI);
NTI101208.kind = 20;
NTI101208.base = (&NTI108);
NTI101208.flags = 3;
TMP141[1].kind = 1;
TMP141[1].offset = offsetof(timeinfo101205, Second);
TMP141[1].typ = (&NTI101208);
TMP141[1].name = "second";
TMP146[1] = &TMP141[2];
NTI101211.size = sizeof(NI);
NTI101211.kind = 20;
NTI101211.base = (&NTI108);
NTI101211.flags = 3;
TMP141[2].kind = 1;
TMP141[2].offset = offsetof(timeinfo101205, Minute);
TMP141[2].typ = (&NTI101211);
TMP141[2].name = "minute";
TMP146[2] = &TMP141[3];
NTI101213.size = sizeof(NI);
NTI101213.kind = 20;
NTI101213.base = (&NTI108);
NTI101213.flags = 3;
TMP141[3].kind = 1;
TMP141[3].offset = offsetof(timeinfo101205, Hour);
TMP141[3].typ = (&NTI101213);
TMP141[3].name = "hour";
TMP146[3] = &TMP141[4];
NTI101216.size = sizeof(NI);
NTI101216.kind = 20;
NTI101216.base = (&NTI108);
NTI101216.flags = 3;
TMP141[4].kind = 1;
TMP141[4].offset = offsetof(timeinfo101205, Monthday);
TMP141[4].typ = (&NTI101216);
TMP141[4].name = "monthday";
TMP146[4] = &TMP141[5];
NTI101006.size = sizeof(NU8);
NTI101006.kind = 14;
NTI101006.base = 0;
NTI101006.flags = 3;
for (TMP149 = 0; TMP149 < 12; TMP149++) {
TMP141[TMP149+6].kind = 1;
TMP141[TMP149+6].offset = TMP149;
TMP141[TMP149+6].name = TMP148[TMP149];
TMP147[TMP149] = &TMP141[TMP149+6];
}
TMP141[18].len = 12; TMP141[18].kind = 2; TMP141[18].sons = &TMP147[0];
NTI101006.node = &TMP141[18];
TMP141[5].kind = 1;
TMP141[5].offset = offsetof(timeinfo101205, Month);
TMP141[5].typ = (&NTI101006);
TMP141[5].name = "month";
TMP146[5] = &TMP141[19];
NTI101220.size = sizeof(NI);
NTI101220.kind = 20;
NTI101220.base = (&NTI108);
NTI101220.flags = 3;
TMP141[19].kind = 1;
TMP141[19].offset = offsetof(timeinfo101205, Year);
TMP141[19].typ = (&NTI101220);
TMP141[19].name = "year";
TMP146[6] = &TMP141[20];
NTI101008.size = sizeof(NU8);
NTI101008.kind = 14;
NTI101008.base = 0;
NTI101008.flags = 3;
for (TMP152 = 0; TMP152 < 7; TMP152++) {
TMP141[TMP152+21].kind = 1;
TMP141[TMP152+21].offset = TMP152;
TMP141[TMP152+21].name = TMP151[TMP152];
TMP150[TMP152] = &TMP141[TMP152+21];
}
TMP141[28].len = 7; TMP141[28].kind = 2; TMP141[28].sons = &TMP150[0];
NTI101008.node = &TMP141[28];
TMP141[20].kind = 1;
TMP141[20].offset = offsetof(timeinfo101205, Weekday);
TMP141[20].typ = (&NTI101008);
TMP141[20].name = "weekday";
TMP146[7] = &TMP141[29];
NTI101226.size = sizeof(NI);
NTI101226.kind = 20;
NTI101226.base = (&NTI108);
NTI101226.flags = 3;
TMP141[29].kind = 1;
TMP141[29].offset = offsetof(timeinfo101205, Yearday);
TMP141[29].typ = (&NTI101226);
TMP141[29].name = "yearday";
TMP146[8] = &TMP141[30];
TMP141[30].kind = 1;
TMP141[30].offset = offsetof(timeinfo101205, Isdst);
TMP141[30].typ = (&NTI138);
TMP141[30].name = "isDST";
TMP146[9] = &TMP141[31];
TMP141[31].kind = 1;
TMP141[31].offset = offsetof(timeinfo101205, Tzname);
TMP141[31].typ = (&NTI149);
TMP141[31].name = "tzname";
TMP146[10] = &TMP141[32];
TMP141[32].kind = 1;
TMP141[32].offset = offsetof(timeinfo101205, Timezone);
TMP141[32].typ = (&NTI108);
TMP141[32].name = "timezone";
TMP141[0].len = 11; TMP141[0].kind = 2; TMP141[0].sons = &TMP146[0];
NTI101205.node = &TMP141[0];
}

