/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, i386, gcc */
/* Command for C compiler:
   i686-elf-gcc -c  -w -I$lib -ffreestanding -O2 -Wall -Wextra -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/chronize/Documents/projects/nimkernel/nimcache/unsigned.o /home/chronize/Documents/projects/nimkernel/nimcache/unsigned.c */
#define NIM_INTBITS 32
#include "nimbase.h"
NIM_EXTERNC N_NOINLINE(void, HEX00_unsignedInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_unsignedDatInit)(void) {
}

